--- 문의 테이블 ---

DROP TABLE INQUIRY CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_INQUIRY_ID;

CREATE TABLE INQUIRY (
    INQUIRY_ID    NUMBER         NOT NULL,               -- 문의 PK
    MEMBER_ID     NUMBER         NOT NULL,               -- 문의 작성 회원
    TITLE         VARCHAR2(200)  NOT NULL,               -- 문의 제목
    CONTENT       CLOB           NOT NULL,               -- 문의 내용
    CATEGORY      VARCHAR2(50),                          -- 문의 유형(계정, 결제 등)
    STATUS        VARCHAR2(20)   DEFAULT 'RECEIVED' NOT NULL,
    -- RECEIVED / IN_PROGRESS / ANSWERED / CLOSED 등

    CREATED_AT    DATE           DEFAULT SYSDATE NOT NULL,

    CONSTRAINT PK_INQUIRY PRIMARY KEY (INQUIRY_ID),
    CONSTRAINT FK_INQUIRY_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID)
);

COMMENT ON TABLE INQUIRY IS '문의 테이블';

COMMENT ON COLUMN INQUIRY.INQUIRY_ID IS '문의 PK';
COMMENT ON COLUMN INQUIRY.MEMBER_ID  IS '문의 작성 회원 PK';
COMMENT ON COLUMN INQUIRY.TITLE      IS '문의 제목';
COMMENT ON COLUMN INQUIRY.CONTENT    IS '문의 내용';
COMMENT ON COLUMN INQUIRY.CATEGORY   IS '문의 유형';
COMMENT ON COLUMN INQUIRY.STATUS     IS '문의 상태(RECEIVED/ANSWERED 등)';
COMMENT ON COLUMN INQUIRY.CREATED_AT IS '문의 생성 일시';

CREATE SEQUENCE SEQ_INQUIRY_ID
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;

commit;