-- 권한 종류 테이블

DROP TABLE ROLE CASCADE CONSTRAINTS;

CREATE TABLE ROLE (
    ROLE_ID    NUMBER(10)       NOT NULL,
    ROLE_NAME  VARCHAR2(100)    NOT NULL,
    
    CONSTRAINT PK_ROLE PRIMARY KEY (ROLE_ID),
    CONSTRAINT UQ_ROLE_NAME UNIQUE (ROLE_NAME)
);

DROP SEQUENCE SEQ_ROLE_ID;

CREATE SEQUENCE SEQ_ROLE_ID
  START WITH 1                  -- 시작 번호
  INCREMENT BY 1                -- 증가값
  MAXVALUE 9999999999           -- 최대값: 9999999999 --> NUMBER(10) 대응
  CACHE 2                       -- 2번은 메모리에서만 계산
  NOCYCLE;                      -- 다시 1부터 생성되는 것을 방지
  
-- INSERT
INSERT INTO ROLE (ROLE_NAME) 
VALUES ('USER');

INSERT INTO ROLE (ROLE_NAME) 
VALUES ('ADMIN');

-- SELECT
SELECT *
FROM ROLE
ORDER BY ROLE_ID;

-- UPDATE
UPDATE ROLE
SET ROLE_NAME = 'SUPER_ADMIN'
WHERE ROLE_ID = 2;

-- DELETE
DELETE FROM ROLE
WHERE ROLE_ID = 3;


