DROP TABLE AI_MODEL_VERSION CASCADE CONSTRAINTS;

CREATE TABLE AI_MODEL_VERSION (
    MODEL_ID        NUMBER(10)     NOT NULL,
    MODEL_NAME      VARCHAR2(100)  NOT NULL,
    MODEL_VERSION   VARCHAR2(50)   NOT NULL,
    PROVIDER        VARCHAR2(50),
    CREATED_AT      DATE           DEFAULT SYSDATE,
    IS_ACTIVE       CHAR(1)        DEFAULT 'Y',

    CONSTRAINT PK_AI_MODEL_VERSION PRIMARY KEY (MODEL_ID)
);

COMMENT ON TABLE AI_MODEL_VERSION IS 'AI 모델 버전 및 제공자 관리 테이블';

COMMENT ON COLUMN AI_MODEL_VERSION.MODEL_ID IS 'AI 모델 PK';
COMMENT ON COLUMN AI_MODEL_VERSION.MODEL_NAME IS 'AI 모델 이름';
COMMENT ON COLUMN AI_MODEL_VERSION.MODEL_VERSION IS 'AI 모델 버전';
COMMENT ON COLUMN AI_MODEL_VERSION.PROVIDER IS '모델 제공자(OpenAI, Local, HuggingFace)';
COMMENT ON COLUMN AI_MODEL_VERSION.CREATED_AT IS '모델 등록 일시';
COMMENT ON COLUMN AI_MODEL_VERSION.IS_ACTIVE IS '모델 사용 여부(Y/N)';

DROP SEQUENCE SEQ_AI_MODEL_VERSION_ID;

CREATE SEQUENCE SEQ_AI_MODEL_VERSION_ID
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
CACHE 2
NOCYCLE;
