/* =========================================================
   CREATE TABLE: CHAT_DATA_REF (RAG 근거 연결)
      - ASSISTANT 메시지의 MESSAGE_ID에 연결
   ========================================================= */
DROP TABLE CHAT_DATA_REF CASCADE CONSTRAINTS;

CREATE TABLE CHAT_DATA_REF (
  REF_ID       NUMBER        NOT NULL,
  MESSAGE_ID   NUMBER        NOT NULL,      -- ✅ AI 답변 메시지 ID
  CHUNK_ID     NUMBER        NOT NULL,
  SIM_SCORE    NUMBER(10,6)  NOT NULL,

  CONSTRAINT PK_CHAT_DATA_REF PRIMARY KEY (REF_ID),
  CONSTRAINT FK_CHAT_DATA_REF_MESSAGE
    FOREIGN KEY (MESSAGE_ID)
    REFERENCES CHAT_MESSAGE (MESSAGE_ID)
);

COMMENT ON TABLE CHAT_DATA_REF IS 'RAG 근거(Chunk)와 AI 답변 메시지 연결';
COMMENT ON COLUMN CHAT_DATA_REF.MESSAGE_ID IS 'ASSISTANT 메시지 ID';
COMMENT ON COLUMN CHAT_DATA_REF.CHUNK_ID IS '임베딩 청크 ID';
COMMENT ON COLUMN CHAT_DATA_REF.SIM_SCORE IS '유사도 점수';

DROP SEQUENCE SEQ_CHAT_DATA_REF_ID;

CREATE SEQUENCE SEQ_CHAT_DATA_REF_ID
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
CACHE 2
NOCYCLE;

CREATE INDEX IDX_CHAT_DATA_REF_MESSAGE
  ON CHAT_DATA_REF (MESSAGE_ID);

CREATE INDEX IDX_CHAT_DATA_REF_CHUNK
  ON CHAT_DATA_REF (CHUNK_ID);