DROP TABLE CHAT_MESSAGE CASCADE CONSTRAINTS;

CREATE TABLE CHAT_MESSAGE (
  MESSAGE_ID     NUMBER        NOT NULL,
  SESSION_ID     NUMBER        NOT NULL,

  ROLE           VARCHAR2(20)  NOT NULL,    -- USER / ASSISTANT / SYSTEM
  CONTENT        CLOB          NOT NULL,
  CREATED_AT     DATE          DEFAULT SYSDATE NOT NULL,

  MODEL          VARCHAR2(50),
  TOKENS_IN      NUMBER,
  TOKENS_OUT     NUMBER,

  CONSTRAINT PK_CHAT_MESSAGE PRIMARY KEY (MESSAGE_ID),
  CONSTRAINT FK_CHAT_MESSAGE_SESSION
    FOREIGN KEY (SESSION_ID)
    REFERENCES CHAT_SESSION (SESSION_ID)
);

COMMENT ON TABLE CHAT_MESSAGE IS '챗봇 메시지(단일 메시지 단위: ROLE+CONTENT)';
COMMENT ON COLUMN CHAT_MESSAGE.ROLE IS 'USER/ASSISTANT/SYSTEM';
COMMENT ON COLUMN CHAT_MESSAGE.CONTENT IS '메시지 본문';

DROP SEQUENCE SEQ_CHAT_MESSAGE_ID;

CREATE SEQUENCE SEQ_CHAT_MESSAGE_ID
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
CACHE 2
NOCYCLE;

-- ✅ 세션별 메시지 조회 성능 인덱스
CREATE INDEX IDX_CHAT_MESSAGE_SESSION_TIME
  ON CHAT_MESSAGE (SESSION_ID, CREATED_AT);
