DROP TABLE CHAT_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE CHAT_HISTORY (
    CHAT_ID         NUMBER(10)     NOT NULL,
    SESSION_ID      NUMBER(10)     NOT NULL,
    SENDER_TYPE     VARCHAR2(20)   NOT NULL,
    MESSAGE_CONTENT CLOB           NOT NULL,
    CREATED_AT      DATE           DEFAULT SYSDATE,

    CONSTRAINT PK_CHAT_HISTORY PRIMARY KEY (CHAT_ID),
    CONSTRAINT FK_CHAT_HISTORY_SESSION
        FOREIGN KEY (SESSION_ID)
        REFERENCES CHAT_SESSION(SESSION_ID)
);

COMMENT ON TABLE CHAT_HISTORY IS '채팅 메시지 기록 테이블';
COMMENT ON COLUMN CHAT_HISTORY.CHAT_ID IS '채팅 PK';
COMMENT ON COLUMN CHAT_HISTORY.SESSION_ID IS '세션 FK';
COMMENT ON COLUMN CHAT_HISTORY.SENDER_TYPE IS '발신자 유형(USER, AI)';
COMMENT ON COLUMN CHAT_HISTORY.MESSAGE_CONTENT IS '메시지 내용';
COMMENT ON COLUMN CHAT_HISTORY.CREATED_AT IS '메시지 생성 시간';

DROP SEQUENCE SEQ_CHAT_HISTORY_ID;

CREATE SEQUENCE SEQ_CHAT_HISTORY_ID
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
CACHE 2
NOCYCLE;
