DROP TABLE CHAT_SESSION CASCADE CONSTRAINTS;

CREATE TABLE CHAT_SESSION (
    SESSION_ID      NUMBER(10)      NOT NULL,
    MEMBER_ID       NUMBER(10)      NOT NULL,
    START_TIME      DATE            DEFAULT SYSDATE,
    END_TIME        DATE,
    SESSION_STATUS  VARCHAR2(20)    DEFAULT 'ACTIVE',
    TITLE           VARCHAR2(200),

    CONSTRAINT PK_CHAT_SESSION PRIMARY KEY (SESSION_ID),
    CONSTRAINT FK_CHAT_SESSION_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID)
);

COMMENT ON TABLE CHAT_SESSION IS '대화 세션 테이블';
COMMENT ON COLUMN CHAT_SESSION.SESSION_ID IS '세션 PK';
COMMENT ON COLUMN CHAT_SESSION.MEMBER_ID IS '회원 FK';
COMMENT ON COLUMN CHAT_SESSION.START_TIME IS '세션 시작 시간';
COMMENT ON COLUMN CHAT_SESSION.END_TIME IS '세션 종료 시간';
COMMENT ON COLUMN CHAT_SESSION.SESSION_STATUS IS '세션 상태';
COMMENT ON COLUMN CHAT_SESSION.TITLE IS '세션 제목';

DROP SEQUENCE SEQ_SESSION_ID;

CREATE SEQUENCE SEQ_SESSION_ID
  START WITH 1                  -- 시작 번호
  INCREMENT BY 1                -- 증가값
  MAXVALUE 9999999999           -- 최대값: 9999999999 --> NUMBER(10) 대응
  CACHE 2                       -- 2번은 메모리에서만 계산
  NOCYCLE;                      -- 다시 1부터 생성되는 것을 방지
  
  
  