CREATE TABLE CHAT_DATA_REF (
    REF_ID          NUMBER PRIMARY KEY,
    CHAT_ID         NUMBER NOT NULL,
    DATA_TYPE       VARCHAR2(50), -- REAL_ESTATE, FILE, ETC
    DATA_ID         NUMBER,
    CREATED_AT      DATE DEFAULT SYSDATE,

    CONSTRAINT FK_REF_CHAT
        FOREIGN KEY (CHAT_ID)
        REFERENCES CHAT_HISTORY(CHAT_ID)
);
