DROP TABLE EMBEDDING_CHUNK CASCADE CONSTRAINTS;

CREATE TABLE EMBEDDING_CHUNK (
    CHUNK_ID    NUMBER(10) NOT NULL,
    FILE_ID     NUMBER(10) NOT NULL,
    CHUNK_TEXT  CLOB NOT NULL,
    VECTOR_DATA CLOB NOT NULL,
    CREATED_AT  DATE DEFAULT SYSDATE,

    CONSTRAINT PK_EMBEDDING_CHUNK PRIMARY KEY (CHUNK_ID),
    CONSTRAINT FK_EMBEDDING_FILE
        FOREIGN KEY (FILE_ID)
        REFERENCES UPLOADED_FILE_INFO(FILE_ID)
);

COMMENT ON TABLE EMBEDDING_CHUNK IS '파일 텍스트 임베딩 단위 저장 테이블';
COMMENT ON COLUMN EMBEDDING_CHUNK.CHUNK_TEXT IS '텍스트 청크';
COMMENT ON COLUMN EMBEDDING_CHUNK.VECTOR_DATA IS '임베딩 벡터(JSON)';

DROP SEQUENCE SEQ_CHUNK_ID;

CREATE SEQUENCE SEQ_CHUNK_ID
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
CACHE 2
NOCYCLE;
