DROP TABLE FILE_PROCESSING_STATUS CASCADE CONSTRAINTS;

CREATE TABLE FILE_PROCESSING_STATUS (
    STATUS_ID       NUMBER(10)   NOT NULL,
    FILE_ID         NUMBER(10)   NOT NULL,
    PROCESS_STATUS  VARCHAR2(30),
    ERROR_MESSAGE   CLOB,
    UPDATED_AT      DATE DEFAULT SYSDATE,

    CONSTRAINT PK_FILE_PROCESSING PRIMARY KEY (STATUS_ID),
    CONSTRAINT FK_FILE_PROCESSING_FILE
        FOREIGN KEY (FILE_ID)
        REFERENCES UPLOADED_FILE_INFO(FILE_ID)
);

COMMENT ON TABLE FILE_PROCESSING_STATUS IS '업로드 파일 처리 상태 관리 테이블';

COMMENT ON COLUMN FILE_PROCESSING_STATUS.STATUS_ID IS '파일 처리 상태 PK';
COMMENT ON COLUMN FILE_PROCESSING_STATUS.FILE_ID IS '업로드 파일 FK';
COMMENT ON COLUMN FILE_PROCESSING_STATUS.PROCESS_STATUS IS '파일 처리 상태(PENDING, PROCESSING, DONE, FAILED)';
COMMENT ON COLUMN FILE_PROCESSING_STATUS.ERROR_MESSAGE IS '파일 처리 중 발생한 에러 메시지';
COMMENT ON COLUMN FILE_PROCESSING_STATUS.UPDATED_AT IS '상태 최종 수정 일시';


DROP SEQUENCE SEQ_FILE_PROCESSING_ID;

CREATE SEQUENCE SEQ_FILE_PROCESSING_ID
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
CACHE 2
NOCYCLE;
