DROP TABLE MESSAGE_FEEDBACK CASCADE CONSTRAINTS;

CREATE TABLE MESSAGE_FEEDBACK (
    FEEDBACK_ID NUMBER(10)    NOT NULL,
    CHAT_ID     NUMBER(10)    NOT NULL,
    MEMBER_ID   NUMBER(10),
    SCORE       NUMBER(1),
    COMMENT     VARCHAR2(500),
    CREATED_AT  DATE DEFAULT SYSDATE,

    CONSTRAINT PK_MESSAGE_FEEDBACK PRIMARY KEY (FEEDBACK_ID),
    CONSTRAINT FK_MESSAGE_FEEDBACK_CHAT
        FOREIGN KEY (CHAT_ID)
        REFERENCES CHAT_HISTORY(CHAT_ID)
);

COMMENT ON TABLE MESSAGE_FEEDBACK IS '채팅 메시지에 대한 사용자 피드백 테이블';

COMMENT ON COLUMN MESSAGE_FEEDBACK.FEEDBACK_ID IS '피드백 PK';
COMMENT ON COLUMN MESSAGE_FEEDBACK.CHAT_ID IS '채팅 FK';
COMMENT ON COLUMN MESSAGE_FEEDBACK.MEMBER_ID IS '피드백 작성 회원 FK';
COMMENT ON COLUMN MESSAGE_FEEDBACK.SCORE IS '응답 만족도 점수(1~5)';
COMMENT ON COLUMN MESSAGE_FEEDBACK.COMMENT IS '피드백 코멘트';
COMMENT ON COLUMN MESSAGE_FEEDBACK.CREATED_AT IS '피드백 생성 일시';

DROP SEQUENCE SEQ_MESSAGE_FEEDBACK_ID;

CREATE SEQUENCE SEQ_MESSAGE_FEEDBACK_ID
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
CACHE 2
NOCYCLE;
