DROP TABLE MODEL_INFERENCES_LOG CASCADE CONSTRAINTS;

CREATE TABLE MODEL_INFERENCES_LOG (
    INFERENCE_ID        NUMBER(10)     NOT NULL,
    CHAT_ID             NUMBER(10),
    MODEL_ID            NUMBER(10),
    PROMPT_TOKENS       NUMBER(10),
    RESPONSE_TOKENS     NUMBER(10),
    RESPONSE_TIME_MS    NUMBER(10),
    CREATED_AT          DATE DEFAULT SYSDATE,

    CONSTRAINT PK_MODEL_INFERENCES_LOG PRIMARY KEY (INFERENCE_ID),
    CONSTRAINT FK_MODEL_INFERENCES_LOG_CHAT
        FOREIGN KEY (CHAT_ID)
        REFERENCES CHAT_HISTORY(CHAT_ID),
    CONSTRAINT FK_MODEL_INFERENCES_LOG_MODEL
        FOREIGN KEY (MODEL_ID)
        REFERENCES AI_MODEL_VERSION(MODEL_ID)
);

COMMENT ON TABLE MODEL_INFERENCES_LOG IS 'AI 모델 추론(응답) 로그 테이블';

COMMENT ON COLUMN MODEL_INFERENCES_LOG.INFERENCE_ID IS 'AI 추론 로그 PK';
COMMENT ON COLUMN MODEL_INFERENCES_LOG.CHAT_ID IS '연관 채팅 FK';
COMMENT ON COLUMN MODEL_INFERENCES_LOG.MODEL_ID IS '사용 AI 모델 FK';
COMMENT ON COLUMN MODEL_INFERENCES_LOG.PROMPT_TOKENS IS '프롬프트 토큰 수';
COMMENT ON COLUMN MODEL_INFERENCES_LOG.RESPONSE_TOKENS IS '응답 토큰 수';
COMMENT ON COLUMN MODEL_INFERENCES_LOG.RESPONSE_TIME_MS IS '응답 소요 시간(ms)';
COMMENT ON COLUMN MODEL_INFERENCES_LOG.CREATED_AT IS '추론 로그 생성 일시';

DROP SEQUENCE SEQ_MODEL_INFERENCES_LOG_ID;

CREATE SEQUENCE SEQ_MODEL_INFERENCES_LOG_ID
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
CACHE 2
NOCYCLE;
