-- ================================
-- RAG 테이블
-- ================================

DROP TABLE CHAT_RAG CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_RAG_ID;

CREATE TABLE CHAT_RAG (
    RAG_ID      NUMBER(10)      NOT NULL,
    SESSION_ID  NUMBER(10)      NOT NULL,
    QUESTION    CLOB            NOT NULL,
    ANSWER      CLOB            NOT NULL,
    CREATED_AT  DATE            DEFAULT SYSDATE NOT NULL,

    CONSTRAINT PK_RAG PRIMARY KEY (RAG_ID),
    CONSTRAINT FK_RAG_SESSION
        FOREIGN KEY (SESSION_ID)
        REFERENCES CHAT_SESSION (SESSION_ID)
);

-- ================================
-- COMMENT
-- ================================

COMMENT ON TABLE CHAT_RAG IS 'RAG 질의 결과 저장 테이블';

COMMENT ON COLUMN CHAT_RAG.RAG_ID IS 'RAG 결과 PK';
COMMENT ON COLUMN CHAT_RAG.SESSION_ID IS '채팅 세션 ID';
COMMENT ON COLUMN CHAT_RAG.QUESTION IS '사용자 질문';
COMMENT ON COLUMN CHAT_RAG.ANSWER IS 'AI 생성 답변';
COMMENT ON COLUMN CHAT_RAG.CREATED_AT IS '질문 생성 시각';

CREATE SEQUENCE SEQ_CHAT_RAG_ID
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
CACHE 2
NOCYCLE;
