DROP TABLE REAL_ESTATE_DATA CASCADE CONSTRAINTS;

CREATE TABLE REAL_ESTATE_DATA (
    REAL_ESTATE_ID  NUMBER(10)     NOT NULL,
    ADDRESS         VARCHAR2(300),
    PRICE           NUMBER(15),
    AREA            NUMBER(10,2),
    BUILD_YEAR      NUMBER(4),
    DATA_SOURCE     VARCHAR2(100),
    CREATED_AT      DATE DEFAULT SYSDATE,

    CONSTRAINT PK_REAL_ESTATE_DATA PRIMARY KEY (REAL_ESTATE_ID)
);

COMMENT ON TABLE REAL_ESTATE_DATA IS '부동산 정보 도메인 데이터 테이블';

COMMENT ON COLUMN REAL_ESTATE_DATA.REAL_ESTATE_ID IS '부동산 데이터 PK';
COMMENT ON COLUMN REAL_ESTATE_DATA.ADDRESS IS '부동산 주소';
COMMENT ON COLUMN REAL_ESTATE_DATA.PRICE IS '거래 가격';
COMMENT ON COLUMN REAL_ESTATE_DATA.AREA IS '면적(㎡)';
COMMENT ON COLUMN REAL_ESTATE_DATA.BUILD_YEAR IS '건축 연도';
COMMENT ON COLUMN REAL_ESTATE_DATA.DATA_SOURCE IS '데이터 출처';
COMMENT ON COLUMN REAL_ESTATE_DATA.CREATED_AT IS '데이터 생성 일시';

DROP SEQUENCE SEQ_REAL_ESTATE_DATA_ID;

CREATE SEQUENCE SEQ_REAL_ESTATE_DATA_ID
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
CACHE 2
NOCYCLE;
