DROP TABLE UPLOADED_FILE_INFO CASCADE CONSTRAINTS;

CREATE TABLE UPLOADED_FILE_INFO (
    FILE_ID       NUMBER(10)    NOT NULL,
    SESSION_ID    NUMBER(10),
    FILE_NAME     VARCHAR2(255),
    FILE_TYPE     VARCHAR2(50),
    FILE_SIZE     NUMBER(10),
    STORAGE_PATH  VARCHAR2(500),
    UPLOADED_AT   DATE DEFAULT SYSDATE,

    CONSTRAINT PK_UPLOADED_FILE PRIMARY KEY (FILE_ID),
    CONSTRAINT FK_UPLOADED_FILE_SESSION
        FOREIGN KEY (SESSION_ID)
        REFERENCES CHAT_SESSION(SESSION_ID)
);

COMMENT ON TABLE UPLOADED_FILE_INFO IS '업로드 파일 정보 테이블';
COMMENT ON COLUMN UPLOADED_FILE_INFO.FILE_ID IS '파일 PK';
COMMENT ON COLUMN UPLOADED_FILE_INFO.SESSION_ID IS '세션 FK';
COMMENT ON COLUMN UPLOADED_FILE_INFO.FILE_NAME IS '파일명';
COMMENT ON COLUMN UPLOADED_FILE_INFO.FILE_TYPE IS '파일 타입';
COMMENT ON COLUMN UPLOADED_FILE_INFO.FILE_SIZE IS '파일 크기';
COMMENT ON COLUMN UPLOADED_FILE_INFO.STORAGE_PATH IS '파일 저장 경로';

DROP SEQUENCE SEQ_UPLOADED_FILE_ID;

CREATE SEQUENCE SEQ_UPLOADED_FILE_ID
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
CACHE 2
NOCYCLE;
