DROP TABLE BOARD_CATEGORY CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_BOARD_CATEGORY_ID;

CREATE TABLE BOARD_CATEGORY (
  CATEGORY_ID    NUMBER(10)      NOT NULL,
  CATEGORY_NAME  VARCHAR2(100)   NOT NULL,

  VISIBLE_YN     CHAR(1)         DEFAULT 'Y' NOT NULL,
  WRITE_POLICY   VARCHAR2(20)    DEFAULT 'LOGIN_ANY' NOT NULL,

  COMMENT_YN     CHAR(1)         DEFAULT 'Y' NOT NULL,
  REPORT_YN      CHAR(1)         DEFAULT 'Y' NOT NULL,
  LIKE_YN        CHAR(1)         DEFAULT 'Y' NOT NULL,
  SECRET_YN      CHAR(1)         DEFAULT 'N' NOT NULL,
  FILE_YN        CHAR(1)         DEFAULT 'Y' NOT NULL,

  SORT_NO        NUMBER(5)       DEFAULT 0 NOT NULL,

  CREATED_AT     DATE            DEFAULT SYSDATE NOT NULL,
  UPDATED_AT     DATE,

  CONSTRAINT PK_BOARD_CATEGORY PRIMARY KEY (CATEGORY_ID),
  CONSTRAINT UQ_BOARD_CATEGORY_NAME UNIQUE (CATEGORY_NAME),

  CONSTRAINT CK_BC_VISIBLE_YN CHECK (VISIBLE_YN IN ('Y','N')),
  CONSTRAINT CK_BC_WRITE_POLICY CHECK (WRITE_POLICY IN ('ADMIN_ONLY','LOGIN_ANY')),

  CONSTRAINT CK_BC_COMMENT_YN CHECK (COMMENT_YN IN ('Y','N')),
  CONSTRAINT CK_BC_REPORT_YN  CHECK (REPORT_YN  IN ('Y','N')),
  CONSTRAINT CK_BC_LIKE_YN    CHECK (LIKE_YN    IN ('Y','N')),
  CONSTRAINT CK_BC_SECRET_YN  CHECK (SECRET_YN  IN ('Y','N')),
  CONSTRAINT CK_BC_FILE_YN    CHECK (FILE_YN    IN ('Y','N'))
);

CREATE INDEX IDX_BC_VISIBLE_SORT ON BOARD_CATEGORY (VISIBLE_YN, SORT_NO, CATEGORY_ID);


CREATE SEQUENCE SEQ_BOARD_CATEGORY_ID
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 9999999999
  CACHE 2
  NOCYCLE;

ALTER TABLE BOARD
  ADD CONSTRAINT FK_BOARD_CATEGORY
  FOREIGN KEY (CATEGORY_ID)
  REFERENCES BOARD_CATEGORY (CATEGORY_ID);