DROP TABLE BOARD_REPORT   CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_BOARD_REPORT_ID;

CREATE TABLE BOARD_REPORT (
  REPORT_ID    NUMBER(10)      NOT NULL,
  BOARD_ID     NUMBER(10)      NOT NULL,
  MEMBER_ID    NUMBER(10)      NOT NULL,

  REASON_CODE  VARCHAR2(50)    NOT NULL,
  REASON_TEXT  VARCHAR2(500),

  CREATED_AT   DATE            DEFAULT SYSDATE NOT NULL,

  CONSTRAINT PK_BOARD_REPORT PRIMARY KEY (REPORT_ID),
  CONSTRAINT FK_REPORT_BOARD FOREIGN KEY (BOARD_ID) REFERENCES BOARD(BOARD_ID),
  CONSTRAINT FK_REPORT_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
  CONSTRAINT UQ_REPORT_BOARD_MEMBER UNIQUE (BOARD_ID, MEMBER_ID)
);

CREATE INDEX IDX_REPORT_BOARD ON BOARD_REPORT (BOARD_ID);

CREATE SEQUENCE SEQ_BOARD_REPORT_ID
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 9999999999
  CACHE 2
  NOCYCLE;