DROP TABLE BOARD_LIKE CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_BOARD_LIKE_ID;

CREATE TABLE BOARD_LIKE (
  LIKE_ID     NUMBER(10)      NOT NULL,
  BOARD_ID    NUMBER(10)      NOT NULL,
  MEMBER_ID   NUMBER(10)      NOT NULL,

  CREATED_AT  DATE            DEFAULT SYSDATE NOT NULL,

  CONSTRAINT PK_BOARD_LIKE PRIMARY KEY (LIKE_ID),
  CONSTRAINT FK_LIKE_BOARD FOREIGN KEY (BOARD_ID) REFERENCES BOARD(BOARD_ID),
  CONSTRAINT FK_LIKE_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
  CONSTRAINT UQ_LIKE_BOARD_MEMBER UNIQUE (BOARD_ID, MEMBER_ID)
);

CREATE INDEX IDX_LIKE_BOARD ON BOARD_LIKE (BOARD_ID);

CREATE SEQUENCE SEQ_BOARD_LIKE_ID
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 9999999999
  CACHE 2
  NOCYCLE;