DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_BOARD_ID;

CREATE TABLE BOARD (
  BOARD_ID       NUMBER(10)       NOT NULL,
  MEMBER_ID      NUMBER(10)       NOT NULL,
  CATEGORY_ID    NUMBER(10)       NOT NULL,
  TITLE          VARCHAR2(2000)   NOT NULL,
  CONTENT        CLOB             NOT NULL,
  IS_SECRET      CHAR(1)          DEFAULT 'N' NOT NULL,
  POST_PASSWORD  VARCHAR2(255),
  VIEW_CNT       NUMBER(10)       DEFAULT 0 NOT NULL,
  PINNED_YN      CHAR(1)          DEFAULT 'N' NOT NULL,
  DELETED_YN     CHAR(1)          DEFAULT 'N' NOT NULL,

  CREATED_AT     DATE             DEFAULT SYSDATE NOT NULL,
  UPDATED_AT     DATE,

  CONSTRAINT PK_BOARD PRIMARY KEY (BOARD_ID),
  CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
  CONSTRAINT FK_BOARD_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES BOARD_CATEGORY(CATEGORY_ID),

  CONSTRAINT CK_BOARD_SECRET CHECK (IS_SECRET IN ('Y','N')),
  CONSTRAINT CK_BOARD_PINNED CHECK (PINNED_YN IN ('Y','N')),
  CONSTRAINT CK_BOARD_DELETED CHECK (DELETED_YN IN ('Y','N'))
);

CREATE INDEX IDX_BOARD_CATEGORY_DATE ON BOARD (CATEGORY_ID, CREATED_AT DESC);

CREATE SEQUENCE SEQ_BOARD_ID
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 9999999999
  CACHE 2
  NOCYCLE;
  