-- ================================
-- 챗봇 검색 차단 청크 테이블
-- ================================
DROP TABLE CHAT_RAG_BLOCKED_CHUNK CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_CHAT_RBC_ID;

CREATE TABLE CHAT_RAG_BLOCKED_CHUNK (
    BLOCK_ID     NUMBER         NOT NULL,
    CHUNK_ID     NUMBER         NOT NULL,
    REASON       VARCHAR2(200),
    CREATED_AT   DATE           DEFAULT SYSDATE NOT NULL,
    CREATED_BY   NUMBER,
    IS_ACTIVE    NUMBER(1)      DEFAULT 1 NOT NULL,

    CONSTRAINT PK_CHAT_RBC 
        PRIMARY KEY (BLOCK_ID),
    CONSTRAINT FK_CHAT_RBC_CHUNK 
        FOREIGN KEY (CHUNK_ID) REFERENCES EMBEDDING_CHUNK(CHUNK_ID),
    CONSTRAINT UK_CHAT_RBC_CHUNK 
        UNIQUE (CHUNK_ID),
    CONSTRAINT CK_CHAT_RBC_ACTIVE 
        CHECK (IS_ACTIVE IN (0,1))
);

CREATE SEQUENCE SEQ_CHAT_RBC_ID
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
CACHE 2
NOCYCLE;