-- =========================================
-- EMBEDDING_CHUNK (refId 기반) 테이블
-- file_id 컬럼은 "ChatDataRef.ref_id"를 저장하는 용도로 사용
-- =========================================
DROP TABLE EMBEDDING_CHUNK CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_CHUNK_ID;

CREATE TABLE EMBEDDING_CHUNK (
    CHUNK_ID        NUMBER(10)  NOT NULL,
    FILE_ID         NUMBER(10)  NOT NULL,        -- ✅ 여기에는 CHAT_DATA_REF.REF_ID가 들어감(설계상)
    CHUNK_TEXT      CLOB        NOT NULL,
    VECTOR_DATA     CLOB        NOT NULL,
    CREATED_AT      DATE        DEFAULT SYSDATE NOT NULL,

    CONSTRAINT PK_EMBEDDING_CHUNK 
        PRIMARY KEY (CHUNK_ID),
    CONSTRAINT FK_EMBEDDING_FILE
        FOREIGN KEY (FILE_ID)REFERENCES CHAT_DATA_REF(REF_ID)
);

COMMENT ON TABLE  EMBEDDING_CHUNK IS 'RAG 검색용 텍스트 청크 임베딩 저장(기준키=CHAT_DATA_REF.REF_ID)';

COMMENT ON COLUMN EMBEDDING_CHUNK.CHUNK_ID    IS '청크 PK';
COMMENT ON COLUMN EMBEDDING_CHUNK.FILE_ID     IS 'CHAT_DATA_REF.REF_ID (참고자료/요약 ref)';
COMMENT ON COLUMN EMBEDDING_CHUNK.CHUNK_TEXT  IS '텍스트 청크';
COMMENT ON COLUMN EMBEDDING_CHUNK.VECTOR_DATA IS '임베딩 벡터(JSON)';
COMMENT ON COLUMN EMBEDDING_CHUNK.CREATED_AT  IS '생성일';

CREATE SEQUENCE SEQ_CHUNK_ID
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
CACHE 20
NOCYCLE;
