/* =========================================================
   CREATE TABLE: CHAT_DATA_REF (RAG 근거 연결)
      - ASSISTANT 메시지의 MESSAGE_ID에 연결
   ========================================================= */
DROP TABLE CHAT_DATA_REF CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_CHAT_DATA_REF_ID;

CREATE TABLE CHAT_DATA_REF (
  DATA_REF_ID   NUMBER        NOT NULL,
  MEMBER_ID     NUMBER        NOT NULL,
  SESSION_ID    NUMBER        NOT NULL,

  REF_TYPE      VARCHAR2(50)  NOT NULL,   -- DOCUMENT_ANALYSIS / CHECKLIST / etc
  TITLE         VARCHAR2(200) NOT NULL,
  SUMMARY       CLOB          NOT NULL,

  CREATED_AT    DATE DEFAULT SYSDATE NOT NULL,

  CONSTRAINT PK_CHAT_DATA_REF PRIMARY KEY (DATA_REF_ID),
  CONSTRAINT FK_CHAT_DATA_REF_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
  CONSTRAINT FK_CHAT_DATA_REF_SESSION FOREIGN KEY (SESSION_ID) REFERENCES CHAT_SESSION(SESSION_ID)
);

CREATE INDEX IDX_CHAT_DATA_REF_MEMBER ON CHAT_DATA_REF(MEMBER_ID);
CREATE INDEX IDX_CHAT_DATA_REF_SESSION ON CHAT_DATA_REF(SESSION_ID);
CREATE INDEX IDX_CHAT_DATA_REF_TYPE ON CHAT_DATA_REF(REF_TYPE);

CREATE SEQUENCE SEQ_CHAT_DATA_REF_ID
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
CACHE 2
NOCYCLE;
