-- ================================
-- 챗봇 메시지 참조 테이블
-- ================================
DROP TABLE CHAT_MESSAGE_REF CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_CHAT_MESSAGE_REF_ID;

CREATE TABLE CHAT_MESSAGE_REF (
    MESSAGE_REF_ID    NUMBER          NOT NULL,
    CHAT_ID           NUMBER          NOT NULL,   -- CHAT_MESSAGE.chat_id
    CHUNK_ID          NUMBER          NOT NULL,
    SCORE             NUMBER(10,6)    NOT NULL,
    RANK_NO           NUMBER(5)       NOT NULL,
    CREATED_AT        DATE DEFAULT    SYSDATE NOT NULL,

    CONSTRAINT PK_CHAT_MESSAGE_REF 
        PRIMARY KEY (MESSAGE_REF_ID),
    CONSTRAINT FK_CHAT_MESSAGE_REF_CHAT 
        FOREIGN KEY (CHAT_ID) REFERENCES CHAT_MESSAGE(CHAT_ID),
    CONSTRAINT FK_CHAT_MESSAGE_REF_CHUNK 
        FOREIGN KEY (CHUNK_ID) REFERENCES EMBEDDING_CHUNK(CHUNK_ID),
    CONSTRAINT UK_CMR_CHAT_CHUNK 
        UNIQUE (CHAT_ID, CHUNK_ID)
);

CREATE SEQUENCE SEQ_CHAT_MESSAGE_REF_ID
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
CACHE 2
NOCYCLE;



