DROP TABLE CHAT_MESSAGE_FEEDBACK CASCADE CONSTRAINTS;

CREATE TABLE CHAT_MESSAGE_FEEDBACK (
  FEEDBACK_ID  NUMBER        NOT NULL,
  CHAT_ID      NUMBER        NOT NULL,   -- 평가 대상(ASSISTANT 메시지)
  MEMBER_ID    NUMBER        NOT NULL,   -- 평가한 사용자
  VALUE        NUMBER(2)     NOT NULL,   -- +1(좋아요), -1(싫어요)
  CREATED_AT   DATE          DEFAULT SYSDATE NOT NULL,
  UPDATED_AT   DATE          DEFAULT SYSDATE NOT NULL,

  CONSTRAINT PK_CHAT_MESSAGE_FEEDBACK PRIMARY KEY (FEEDBACK_ID),

  CONSTRAINT FK_CMF_CHAT
    FOREIGN KEY (CHAT_ID) REFERENCES CHAT_MESSAGE(CHAT_ID),

  CONSTRAINT FK_CMF_MEMBER
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),

  CONSTRAINT UK_CMF_MEMBER_CHAT UNIQUE (MEMBER_ID, CHAT_ID),
  CONSTRAINT CK_CMF_VALUE CHECK (VALUE IN (1, -1))
);

COMMENT ON TABLE CHAT_MESSAGE_FEEDBACK IS 'AI 답변 메시지(ASSISTANT)에 대한 유저 피드백(좋아요/싫어요)';

DROP SEQUENCE SEQ_CHAT_MESSAGE_FEEDBACK_ID;

CREATE SEQUENCE SEQ_CHAT_MESSAGE_FEEDBACK_ID
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
CACHE 2
NOCYCLE;

-- 유저 1명은 메시지 1개에 대해 1번만 평가(토글/변경은 UPDATE)
ALTER TABLE CHAT_MESSAGE_FEEDBACK
  ADD CONSTRAINT UK_CMF_MEMBER_CHAT UNIQUE (MEMBER_ID, CHAT_ID);

