/* =========================================================
 * 체크리스트 최소 ERD (7개 테이블) - Oracle 18c XE 기준
 * - 전제: MEMBER(MEMBER_ID PK) 테이블이 이미 존재
 * - 사후 체크 상태 3값: DONE / NOT_DONE / NOT_REQUIRED
 * ========================================================= */

------------------------------------------------------------
-- 0) 안전 DROP (없어도 에러 안 나게)
------------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHECKLIST_SATISFACTION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHECKLIST_RESPONSE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHECKLIST_SESSION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHECKLIST_ITEM CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE POST_TEMPLATE_ASSIGNMENT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USER_PRE_PROFILE_KEY CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHECKLIST_TEMPLATE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CHECKLIST_TEMPLATE_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CHECKLIST_ITEM_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CHECKLIST_SESSION_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CHECKLIST_RESPONSE_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CHECKLIST_SATISFACTION_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USER_PRE_PROFILE_KEY_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_POST_TEMPLATE_ASSIGNMENT_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

------------------------------------------------------------
-- 1) CHECKLIST_TEMPLATE : 템플릿(버전) 메타
------------------------------------------------------------
CREATE TABLE CHECKLIST_TEMPLATE (
  TEMPLATE_ID      NUMBER          NOT NULL,
  PHASE            VARCHAR2(10)    NOT NULL,  -- PRE / POST
  POST_GROUP_CODE  VARCHAR2(30),              -- 사후 3종 구분 (예: POST_A/B/C). PRE면 NULL
  TEMPLATE_NAME    VARCHAR2(200)   NOT NULL,  -- 화면 표시용 이름
  VERSION_NO       NUMBER          DEFAULT 1 NOT NULL,
  STATUS           VARCHAR2(20)    DEFAULT 'DRAFT' NOT NULL, -- DRAFT/ACTIVE/RETIRED -> 초안 / 사용중 / 사용 종료
  DESCRIPTION      VARCHAR2(1000),

  CREATED_AT       DATE            DEFAULT SYSDATE NOT NULL,
  UPDATED_AT       DATE            DEFAULT SYSDATE NOT NULL,

  CONSTRAINT PK_CHECKLIST_TEMPLATE PRIMARY KEY (TEMPLATE_ID),
  CONSTRAINT CK_TEMPLATE_PHASE CHECK (PHASE IN ('PRE','POST')),
  CONSTRAINT CK_TEMPLATE_STATUS CHECK (STATUS IN ('DRAFT','ACTIVE','RETIRED')),
  CONSTRAINT CK_TEMPLATE_POST_GROUP
    CHECK (
      (PHASE = 'PRE'  AND POST_GROUP_CODE IS NULL)
      OR
      (PHASE = 'POST' AND POST_GROUP_CODE IS NOT NULL)
    )
);

CREATE SEQUENCE SEQ_CHECKLIST_TEMPLATE_ID START WITH 1 INCREMENT BY 1 NOCACHE;

COMMENT ON TABLE  CHECKLIST_TEMPLATE IS '체크리스트 템플릿(사전/사후) 버전 관리 테이블';
COMMENT ON COLUMN CHECKLIST_TEMPLATE.TEMPLATE_ID     IS '템플릿 ID(PK)';
COMMENT ON COLUMN CHECKLIST_TEMPLATE.PHASE           IS '단계(PRE=사전, POST=사후)';
COMMENT ON COLUMN CHECKLIST_TEMPLATE.POST_GROUP_CODE IS '사후 체크리스트 유형 코드(사전은 NULL)';
COMMENT ON COLUMN CHECKLIST_TEMPLATE.TEMPLATE_NAME   IS '템플릿 이름';
COMMENT ON COLUMN CHECKLIST_TEMPLATE.VERSION_NO      IS '버전 번호';
COMMENT ON COLUMN CHECKLIST_TEMPLATE.STATUS          IS '상태(DRAFT/ACTIVE/RETIRED)';
COMMENT ON COLUMN CHECKLIST_TEMPLATE.DESCRIPTION     IS '설명';
COMMENT ON COLUMN CHECKLIST_TEMPLATE.CREATED_AT      IS '생성일';
COMMENT ON COLUMN CHECKLIST_TEMPLATE.UPDATED_AT      IS '수정일';

-- 같은 그룹(PHASE+POST_GROUP_CODE)에서 버전 중복 방지
CREATE UNIQUE INDEX UQ_TEMPLATE_GROUP_VER
ON CHECKLIST_TEMPLATE (PHASE, NVL(POST_GROUP_CODE,'_'), VERSION_NO);

------------------------------------------------------------
-- 2) CHECKLIST_ITEM : 템플릿별 항목
------------------------------------------------------------
CREATE TABLE CHECKLIST_ITEM (
  ITEM_ID        NUMBER          NOT NULL,
  TEMPLATE_ID    NUMBER          NOT NULL,
  ITEM_ORDER     NUMBER          NOT NULL,
  TITLE          VARCHAR2(300)   NOT NULL,
  DESCRIPTION    VARCHAR2(2000),
  REQUIRED_YN    CHAR(1)         DEFAULT 'N' NOT NULL, -- Y/N
  ACTIVE_YN      CHAR(1)         DEFAULT 'Y' NOT NULL, -- Y/N (항목 비활성화용)

  CREATED_AT     DATE            DEFAULT SYSDATE NOT NULL,
  UPDATED_AT     DATE            DEFAULT SYSDATE NOT NULL,

  CONSTRAINT PK_CHECKLIST_ITEM PRIMARY KEY (ITEM_ID),
  CONSTRAINT FK_ITEM_TEMPLATE FOREIGN KEY (TEMPLATE_ID) REFERENCES CHECKLIST_TEMPLATE(TEMPLATE_ID),
  CONSTRAINT CK_ITEM_REQUIRED CHECK (REQUIRED_YN IN ('Y','N')),
  CONSTRAINT CK_ITEM_ACTIVE   CHECK (ACTIVE_YN IN ('Y','N'))
);

CREATE SEQUENCE SEQ_CHECKLIST_ITEM_ID START WITH 1 INCREMENT BY 1 NOCACHE;

COMMENT ON TABLE  CHECKLIST_ITEM IS '체크리스트 템플릿에 속한 항목(문구/설명/순서)';
COMMENT ON COLUMN CHECKLIST_ITEM.ITEM_ID     IS '항목 ID(PK)';
COMMENT ON COLUMN CHECKLIST_ITEM.TEMPLATE_ID IS '템플릿 ID(FK)';
COMMENT ON COLUMN CHECKLIST_ITEM.ITEM_ORDER  IS '출력 순서';
COMMENT ON COLUMN CHECKLIST_ITEM.TITLE       IS '항목 제목';
COMMENT ON COLUMN CHECKLIST_ITEM.DESCRIPTION IS '항목 설명/권고 문구';
COMMENT ON COLUMN CHECKLIST_ITEM.REQUIRED_YN IS '필수 여부(Y/N)';
COMMENT ON COLUMN CHECKLIST_ITEM.ACTIVE_YN   IS '사용 여부(Y/N)';
COMMENT ON COLUMN CHECKLIST_ITEM.CREATED_AT  IS '생성일';
COMMENT ON COLUMN CHECKLIST_ITEM.UPDATED_AT  IS '수정일';

-- 한 템플릿 내 순서 중복 방지
CREATE UNIQUE INDEX UQ_ITEM_ORDER_PER_TEMPLATE
ON CHECKLIST_ITEM (TEMPLATE_ID, ITEM_ORDER);

------------------------------------------------------------
-- 3) USER_PRE_PROFILE_KEY : 사전 체크 결과 요약 키(그룹핑)
------------------------------------------------------------
CREATE TABLE USER_PRE_PROFILE_KEY (
  PROFILE_KEY_ID   NUMBER         NOT NULL,
  KEY_HASH         VARCHAR2(64)   NOT NULL,  -- sha256 등 해시 문자열(권장)
  KEY_JSON         CLOB           NOT NULL,  -- 사전 체크 결과 요약(나이대/경험/응답 요약)
  CREATED_AT       DATE           DEFAULT SYSDATE NOT NULL,

  CONSTRAINT PK_USER_PRE_PROFILE_KEY PRIMARY KEY (PROFILE_KEY_ID),
  CONSTRAINT UQ_PROFILE_KEY_HASH UNIQUE (KEY_HASH)
);

CREATE SEQUENCE SEQ_USER_PRE_PROFILE_KEY_ID START WITH 1 INCREMENT BY 1 NOCACHE;

COMMENT ON TABLE  USER_PRE_PROFILE_KEY IS '사전 체크 결과를 요약한 프로필 키(동일 사전 결과 그룹핑)';
COMMENT ON COLUMN USER_PRE_PROFILE_KEY.PROFILE_KEY_ID IS '프로필 키 ID(PK)';
COMMENT ON COLUMN USER_PRE_PROFILE_KEY.KEY_HASH       IS '요약값 해시(유니크)';
COMMENT ON COLUMN USER_PRE_PROFILE_KEY.KEY_JSON       IS '요약 원문(JSON)';
COMMENT ON COLUMN USER_PRE_PROFILE_KEY.CREATED_AT     IS '생성일';

------------------------------------------------------------
-- 4) POST_TEMPLATE_ASSIGNMENT : 사전 프로필키 -> 사후 템플릿(버전) 매핑
------------------------------------------------------------
CREATE TABLE POST_TEMPLATE_ASSIGNMENT (
  ASSIGNMENT_ID    NUMBER        NOT NULL,
  PROFILE_KEY_ID   NUMBER        NOT NULL,
  POST_GROUP_CODE  VARCHAR2(30)  NOT NULL,   -- POST_A/B/C
  TEMPLATE_ID      NUMBER        NOT NULL,   -- 실제 제공할 POST 템플릿(버전)
  ACTIVE_YN        CHAR(1)       DEFAULT 'Y' NOT NULL,
  CREATED_AT       DATE          DEFAULT SYSDATE NOT NULL,
  UPDATED_AT       DATE          DEFAULT SYSDATE NOT NULL,

  CONSTRAINT PK_POST_TEMPLATE_ASSIGNMENT PRIMARY KEY (ASSIGNMENT_ID),
  CONSTRAINT FK_ASSIGN_PROFILE_KEY FOREIGN KEY (PROFILE_KEY_ID) REFERENCES USER_PRE_PROFILE_KEY(PROFILE_KEY_ID),
  CONSTRAINT FK_ASSIGN_TEMPLATE    FOREIGN KEY (TEMPLATE_ID)    REFERENCES CHECKLIST_TEMPLATE(TEMPLATE_ID),
  CONSTRAINT CK_ASSIGN_ACTIVE      CHECK (ACTIVE_YN IN ('Y','N'))
);

CREATE SEQUENCE SEQ_POST_TEMPLATE_ASSIGNMENT_ID START WITH 1 INCREMENT BY 1 NOCACHE;

COMMENT ON TABLE  POST_TEMPLATE_ASSIGNMENT IS '사전 프로필키 기준 사후 체크리스트(유형/버전) 제공 매핑';
COMMENT ON COLUMN POST_TEMPLATE_ASSIGNMENT.ASSIGNMENT_ID   IS '매핑 ID(PK)';
COMMENT ON COLUMN POST_TEMPLATE_ASSIGNMENT.PROFILE_KEY_ID  IS '사전 프로필키 ID(FK)';
COMMENT ON COLUMN POST_TEMPLATE_ASSIGNMENT.POST_GROUP_CODE IS '사후 유형 코드(POST_A/B/C)';
COMMENT ON COLUMN POST_TEMPLATE_ASSIGNMENT.TEMPLATE_ID     IS '제공할 사후 템플릿 ID(FK)';
COMMENT ON COLUMN POST_TEMPLATE_ASSIGNMENT.ACTIVE_YN       IS '활성 여부(Y/N)';
COMMENT ON COLUMN POST_TEMPLATE_ASSIGNMENT.CREATED_AT      IS '생성일';
COMMENT ON COLUMN POST_TEMPLATE_ASSIGNMENT.UPDATED_AT      IS '수정일';

-- 동일 프로필키 + 사후유형에서 활성 매핑이 1개만 존재하도록(운영상 유리)
-- (Oracle은 부분 unique가 없으니, 우선 전체 unique로 강제 + ACTIVE 관리로 운용)
CREATE UNIQUE INDEX UQ_ASSIGN_PROFILE_GROUP
ON POST_TEMPLATE_ASSIGNMENT (PROFILE_KEY_ID, POST_GROUP_CODE);

------------------------------------------------------------
-- 5) CHECKLIST_SESSION : 사용자 진행 단위(버전 고정)
------------------------------------------------------------
CREATE TABLE CHECKLIST_SESSION (
  SESSION_ID      NUMBER         NOT NULL,
  MEMBER_ID       NUMBER         NOT NULL, -- FK to MEMBER
  PHASE           VARCHAR2(10)   NOT NULL, -- PRE/POST
  TEMPLATE_ID     NUMBER         NOT NULL, -- 어떤 버전으로 진행했는지 고정
  PROFILE_KEY_ID  NUMBER,                 -- POST 세션이면 어떤 사전 프로필키로 배정됐는지 추적(선택이지만 추천)

  STARTED_AT      DATE           DEFAULT SYSDATE NOT NULL,
  COMPLETED_AT    DATE,
  STATUS          VARCHAR2(20)   DEFAULT 'IN_PROGRESS' NOT NULL, -- IN_PROGRESS/COMPLETED

  CONSTRAINT PK_CHECKLIST_SESSION PRIMARY KEY (SESSION_ID),
  CONSTRAINT FK_SESSION_TEMPLATE FOREIGN KEY (TEMPLATE_ID) REFERENCES CHECKLIST_TEMPLATE(TEMPLATE_ID),
  CONSTRAINT FK_SESSION_PROFILE  FOREIGN KEY (PROFILE_KEY_ID) REFERENCES USER_PRE_PROFILE_KEY(PROFILE_KEY_ID),
  CONSTRAINT CK_SESSION_PHASE    CHECK (PHASE IN ('PRE','POST')),
  CONSTRAINT CK_SESSION_STATUS   CHECK (STATUS IN ('IN_PROGRESS','COMPLETED')),
  CONSTRAINT CK_SESSION_PROFILE_RULE
    CHECK (
      (PHASE = 'PRE'  AND PROFILE_KEY_ID IS NULL)
      OR
      (PHASE = 'POST' AND PROFILE_KEY_ID IS NOT NULL)
    )
);

CREATE SEQUENCE SEQ_CHECKLIST_SESSION_ID START WITH 1 INCREMENT BY 1 NOCACHE;

COMMENT ON TABLE  CHECKLIST_SESSION IS '사용자 체크리스트 진행 세션(템플릿 버전 고정)';
COMMENT ON COLUMN CHECKLIST_SESSION.SESSION_ID     IS '세션 ID(PK)';
COMMENT ON COLUMN CHECKLIST_SESSION.MEMBER_ID      IS '회원 ID(FK: MEMBER.MEMBER_ID)';
COMMENT ON COLUMN CHECKLIST_SESSION.PHASE          IS '단계(PRE/POST)';
COMMENT ON COLUMN CHECKLIST_SESSION.TEMPLATE_ID    IS '진행한 템플릿(버전) ID(FK)';
COMMENT ON COLUMN CHECKLIST_SESSION.PROFILE_KEY_ID IS '사전 프로필키(POST 세션 추적용)';
COMMENT ON COLUMN CHECKLIST_SESSION.STARTED_AT     IS '시작일시';
COMMENT ON COLUMN CHECKLIST_SESSION.COMPLETED_AT   IS '완료일시';
COMMENT ON COLUMN CHECKLIST_SESSION.STATUS         IS '진행상태(IN_PROGRESS/COMPLETED)';

------------------------------------------------------------
-- 6) CHECKLIST_RESPONSE : 세션별 항목 응답(3값)
------------------------------------------------------------
CREATE TABLE CHECKLIST_RESPONSE (
  RESPONSE_ID     NUMBER        NOT NULL,
  SESSION_ID      NUMBER        NOT NULL,
  ITEM_ID         NUMBER        NOT NULL,
  CHECK_STATUS    VARCHAR2(20)  NOT NULL, -- DONE / NOT_DONE / NOT_REQUIRED
  UPDATED_AT      DATE          DEFAULT SYSDATE NOT NULL,

  CONSTRAINT PK_CHECKLIST_RESPONSE PRIMARY KEY (RESPONSE_ID),
  CONSTRAINT FK_RESP_SESSION FOREIGN KEY (SESSION_ID) REFERENCES CHECKLIST_SESSION(SESSION_ID),
  CONSTRAINT FK_RESP_ITEM    FOREIGN KEY (ITEM_ID)    REFERENCES CHECKLIST_ITEM(ITEM_ID),
  CONSTRAINT CK_RESP_STATUS  CHECK (CHECK_STATUS IN ('DONE','NOT_DONE','NOT_REQUIRED'))
);

CREATE SEQUENCE SEQ_CHECKLIST_RESPONSE_ID START WITH 1 INCREMENT BY 1 NOCACHE;

COMMENT ON TABLE  CHECKLIST_RESPONSE IS '세션 내 항목별 응답(권고형 3상태)';
COMMENT ON COLUMN CHECKLIST_RESPONSE.RESPONSE_ID  IS '응답 ID(PK)';
COMMENT ON COLUMN CHECKLIST_RESPONSE.SESSION_ID   IS '세션 ID(FK)';
COMMENT ON COLUMN CHECKLIST_RESPONSE.ITEM_ID      IS '항목 ID(FK)';
COMMENT ON COLUMN CHECKLIST_RESPONSE.CHECK_STATUS IS '상태(DONE/NOT_DONE/NOT_REQUIRED)';
COMMENT ON COLUMN CHECKLIST_RESPONSE.UPDATED_AT   IS '수정일시';

-- 세션 내 같은 ITEM 중복 저장 방지
CREATE UNIQUE INDEX UQ_RESP_SESSION_ITEM
ON CHECKLIST_RESPONSE (SESSION_ID, ITEM_ID);

------------------------------------------------------------
-- 7) CHECKLIST_SATISFACTION : 만족도(별점/코멘트)
------------------------------------------------------------
CREATE TABLE CHECKLIST_SATISFACTION (
  SATISFACTION_ID  NUMBER         NOT NULL,
  SESSION_ID       NUMBER         NOT NULL,
  RATING           NUMBER         NOT NULL, -- 1~5
  COMMENT_TEXT     VARCHAR2(2000),
  CREATED_AT       DATE           DEFAULT SYSDATE NOT NULL,

  CONSTRAINT PK_CHECKLIST_SATISFACTION PRIMARY KEY (SATISFACTION_ID),
  CONSTRAINT FK_SAT_SESSION FOREIGN KEY (SESSION_ID) REFERENCES CHECKLIST_SESSION(SESSION_ID),
  CONSTRAINT CK_SAT_RATING CHECK (RATING BETWEEN 1 AND 5)
);

CREATE SEQUENCE SEQ_CHECKLIST_SATISFACTION_ID START WITH 1 INCREMENT BY 1 NOCACHE;

COMMENT ON TABLE  CHECKLIST_SATISFACTION IS '체크리스트 만족도(별점/코멘트) - 보통 사후 세션 대상';
COMMENT ON COLUMN CHECKLIST_SATISFACTION.SATISFACTION_ID IS '만족도 ID(PK)';
COMMENT ON COLUMN CHECKLIST_SATISFACTION.SESSION_ID      IS '세션 ID(FK)';
COMMENT ON COLUMN CHECKLIST_SATISFACTION.RATING          IS '별점(1~5)';
COMMENT ON COLUMN CHECKLIST_SATISFACTION.COMMENT_TEXT    IS '코멘트';
COMMENT ON COLUMN CHECKLIST_SATISFACTION.CREATED_AT      IS '작성일';

-- 한 세션에 만족도 1개만
CREATE UNIQUE INDEX UQ_SAT_SESSION
ON CHECKLIST_SATISFACTION (SESSION_ID);

------------------------------------------------------------
-- 8) MEMBER FK는 사용자 DB에 이미 있다고 가정하므로,
--    FK 추가는 선택: MEMBER 테이블/컬럼명이 다를 수 있어 주석 처리
------------------------------------------------------------
 ALTER TABLE CHECKLIST_SESSION
   ADD CONSTRAINT FK_SESSION_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID);
   
commit;
