DROP TABLE BOARD_COMMENT  CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_BOARD_COMMENT_ID;

CREATE TABLE BOARD_COMMENT (
  COMMENT_ID   NUMBER(10)        NOT NULL,
  BOARD_ID     NUMBER(10)        NOT NULL,
  MEMBER_ID    NUMBER(10)        NOT NULL,
  PARENT_ID    NUMBER(10),

  CONTENT      VARCHAR2(1000)    NOT NULL,
  IS_SECRET    CHAR(1)           DEFAULT 'N' NOT NULL,
  DELETED_YN   CHAR(1)           DEFAULT 'N' NOT NULL,

  CREATED_AT   DATE              DEFAULT SYSDATE NOT NULL,
  UPDATED_AT   DATE,

  CONSTRAINT PK_BOARD_COMMENT PRIMARY KEY (COMMENT_ID),
  CONSTRAINT FK_COMMENT_BOARD FOREIGN KEY (BOARD_ID) REFERENCES BOARD(BOARD_ID),
  CONSTRAINT FK_COMMENT_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
  CONSTRAINT FK_COMMENT_PARENT FOREIGN KEY (PARENT_ID) REFERENCES BOARD_COMMENT(COMMENT_ID),

  CONSTRAINT CK_COMMENT_SECRET CHECK (IS_SECRET IN ('Y','N')),
  CONSTRAINT CK_COMMENT_DELETED CHECK (DELETED_YN IN ('Y','N'))
);

CREATE INDEX IDX_COMMENT_BOARD_DATE ON BOARD_COMMENT (BOARD_ID, CREATED_AT, COMMENT_ID);

CREATE SEQUENCE SEQ_BOARD_COMMENT_ID
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 9999999999
  CACHE 2
  NOCYCLE;