DROP TABLE BOARD_PHOTO    CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_BOARD_PHOTO_ID;

CREATE TABLE BOARD_PHOTO (
  PHOTO_ID     NUMBER(10)       NOT NULL,
  BOARD_ID     NUMBER(10)       NOT NULL,

  SAVED_NAME   VARCHAR2(255)    NOT NULL,
  THUMB_NAME   VARCHAR2(255),

  CREATED_AT   DATE             DEFAULT SYSDATE NOT NULL,

  CONSTRAINT PK_BOARD_PHOTO PRIMARY KEY (PHOTO_ID),
  CONSTRAINT FK_BOARD_PHOTO_BOARD FOREIGN KEY (BOARD_ID) REFERENCES BOARD(BOARD_ID)
);

CREATE INDEX IDX_BOARD_PHOTO_BOARD ON BOARD_PHOTO (BOARD_ID);

CREATE SEQUENCE SEQ_BOARD_PHOTO_ID
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 9999999999
  CACHE 2
  NOCYCLE;