--- 답변 테이블 ---

DROP TABLE INQUIRY_ANSWER CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_INQUIRY_ANSWER_ID;

CREATE TABLE INQUIRY_ANSWER (
    ANSWER_ID      NUMBER        NOT NULL,              -- 답변 PK
    INQUIRY_ID     NUMBER        NOT NULL,              -- 어떤 문의에 대한 답변인지
    ADMIN_ID       NUMBER        NOT NULL,              -- 답변한 관리자 MEMBER_ID
    CONTENT        CLOB          NOT NULL,              -- 답변 내용
    CREATED_AT     DATE          DEFAULT SYSDATE NOT NULL,
    UPDATED_AT     DATE,

    CONSTRAINT PK_INQUIRY_ANSWER PRIMARY KEY (ANSWER_ID),

    CONSTRAINT FK_INQUIRY_ANSWER_INQUIRY
        FOREIGN KEY (INQUIRY_ID)
        REFERENCES INQUIRY(INQUIRY_ID)
        ON DELETE CASCADE,

    CONSTRAINT FK_INQUIRY_ANSWER_ADMIN
        FOREIGN KEY (ADMIN_ID)
        REFERENCES MEMBER(MEMBER_ID)
);

COMMENT ON TABLE INQUIRY_ANSWER IS '1:1 문의 답변 테이블';

COMMENT ON COLUMN INQUIRY_ANSWER.ANSWER_ID  IS '문의 답변 PK';
COMMENT ON COLUMN INQUIRY_ANSWER.INQUIRY_ID IS '답변이 달린 문의 PK';
COMMENT ON COLUMN INQUIRY_ANSWER.ADMIN_ID   IS '답변 작성 관리자 PK(MEMBER 참조)';
COMMENT ON COLUMN INQUIRY_ANSWER.CONTENT    IS '답변 내용';
COMMENT ON COLUMN INQUIRY_ANSWER.CREATED_AT IS '답변 생성 일시';
COMMENT ON COLUMN INQUIRY_ANSWER.UPDATED_AT IS '답변 수정 일시';

CREATE SEQUENCE SEQ_INQUIRY_ANSWER_ID
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;

commit;