--- 비밀번호 재설정 관리 테이블 ---

DROP TABLE PASSWORD_RESET CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_PASSWORD_RESET_ID;

CREATE TABLE PASSWORD_RESET (
    RESET_ID      NUMBER         NOT NULL,              -- PK
    MEMBER_ID     NUMBER         NOT NULL,              -- MEMBER 참조
    RESET_CODE    VARCHAR2(100)  NOT NULL,              -- 비밀번호 재설정 코드
    EXPIRES_AT    DATE           NOT NULL,              -- 코드 만료 시간
    USED_YN       CHAR(1)        DEFAULT 'N' NOT NULL,  -- 사용 여부
    USED_AT       DATE,                                 -- 사용된 시각
    CREATED_AT    DATE           DEFAULT SYSDATE NOT NULL, -- 생성 시각

    CONSTRAINT PK_PASSWORD_RESET PRIMARY KEY (RESET_ID),
    CONSTRAINT UQ_PASSWORD_RESET_CODE UNIQUE (RESET_CODE),
    CONSTRAINT FK_PASSWORD_RESET_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID)
        ON DELETE CASCADE
);

COMMENT ON TABLE PASSWORD_RESET IS '비밀번호 재설정 관리 테이블';

COMMENT ON COLUMN PASSWORD_RESET.RESET_ID     IS '비밀번호 재설정 PK';
COMMENT ON COLUMN PASSWORD_RESET.MEMBER_ID    IS '회원 PK (MEMBER 참조)';
COMMENT ON COLUMN PASSWORD_RESET.RESET_CODE   IS '비밀번호 재설정 코드';
COMMENT ON COLUMN PASSWORD_RESET.EXPIRES_AT   IS '코드 만료 일시';
COMMENT ON COLUMN PASSWORD_RESET.USED_YN      IS '코드 사용 여부(Y/N)';
COMMENT ON COLUMN PASSWORD_RESET.USED_AT      IS '코드 사용 일시';
COMMENT ON COLUMN PASSWORD_RESET.CREATED_AT   IS '재설정 요청 생성 일시';

CREATE SEQUENCE SEQ_PASSWORD_RESET_ID
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;

commit;