--- 이메일 인증 토큰 관리 테이블 ---

DROP TABLE EMAIL_VERIFICATION CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_EMAIL_VERIFICATION_ID;

CREATE TABLE EMAIL_VERIFICATION (
    VERIFICATION_ID   NUMBER         NOT NULL,
    EMAIL             VARCHAR2(255)  NOT NULL,
    VERIFY_CODE       VARCHAR2(10)   NOT NULL,
    EXPIRES_AT        DATE           NOT NULL,
    VERIFIED_YN       CHAR(1)         DEFAULT 'N' NOT NULL,
    VERIFIED_AT       DATE,
    CREATED_AT        DATE            DEFAULT SYSDATE NOT NULL,

    CONSTRAINT PK_EMAIL_VERIFICATION PRIMARY KEY (VERIFICATION_ID),
    CONSTRAINT UQ_EMAIL_VERIFICATION_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UQ_EMAIL_VERIFICATION_CODE UNIQUE (VERIFY_CODE)
);

CREATE SEQUENCE SEQ_EMAIL_VERIFICATION_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

COMMENT ON TABLE EMAIL_VERIFICATION IS '회원가입 전 이메일 인증 테이블';
