DROP TABLE CHAT_RAG_BLOCKED_CHUNK CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_CHAT_BLOCKED_CHUNK_ID;

CREATE TABLE CHAT_RAG_BLOCKED_CHUNK (
  BLOCKED_CHUNK_ID     NUMBER NOT NULL,
  REASON       VARCHAR2(200),
  CREATED_AT   DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_RAG_BLOCKED_CHUNK PRIMARY KEY (BLOCKED_CHUNK_ID),
  CONSTRAINT FK_RBC_CHUNK FOREIGN KEY (BLOCKED_CHUNK_ID) REFERENCES EMBEDDING_CHUNK(CHUNK_ID)
);

CREATE SEQUENCE SEQ_CHAT_BLOCKED_CHUNK_ID
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
CACHE 2
NOCYCLE;