DROP TABLE BOARD_FILE     CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_BOARD_FILE_ID;

CREATE TABLE BOARD_FILE (
  FILE_ID        NUMBER(10)       NOT NULL,
  BOARD_ID       NUMBER(10)       NOT NULL,

  ORIGINAL_NAME  VARCHAR2(255)    NOT NULL,
  SAVED_NAME     VARCHAR2(255)    NOT NULL,
  FILE_SIZE      NUMBER(15)       DEFAULT 0 NOT NULL,

  CREATED_AT     DATE             DEFAULT SYSDATE NOT NULL,

  CONSTRAINT PK_BOARD_FILE PRIMARY KEY (FILE_ID),
  CONSTRAINT FK_BOARD_FILE_BOARD FOREIGN KEY (BOARD_ID) REFERENCES BOARD(BOARD_ID)
);

CREATE INDEX IDX_BOARD_FILE_BOARD ON BOARD_FILE (BOARD_ID);

CREATE SEQUENCE SEQ_BOARD_FILE_ID
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 9999999999
  CACHE 2
  NOCYCLE;