--- 회원 활동 로그 테이블 ---

DROP TABLE ACTIVITY_LOG CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_ACTIVITY_LOG_ID;

CREATE TABLE ACTIVITY_LOG (
    LOG_ID        NUMBER         NOT NULL,              -- 활동 로그 PK
    MEMBER_ID     NUMBER         NOT NULL,              -- 활동한 회원
    ACTION_TYPE   VARCHAR2(100)  NOT NULL,              -- 활동 유형
    ACTION_DETAIL VARCHAR2(500),                        -- 상세 내용(선택)
    ACTION_AT     DATE           DEFAULT SYSDATE NOT NULL, -- 활동 일시
    ACTION_IP     VARCHAR2(50),                         -- 행동 IP
    USER_AGENT    VARCHAR2(300),                        -- 브라우저/기기 정보

    CONSTRAINT PK_ACTIVITY_LOG PRIMARY KEY (LOG_ID),
    CONSTRAINT FK_ACTIVITY_LOG_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID)
);

COMMENT ON TABLE ACTIVITY_LOG IS '회원 활동 로그 테이블';

COMMENT ON COLUMN ACTIVITY_LOG.LOG_ID        IS '활동 로그 PK';
COMMENT ON COLUMN ACTIVITY_LOG.MEMBER_ID     IS '회원 PK(MEMBER 참조)';
COMMENT ON COLUMN ACTIVITY_LOG.ACTION_TYPE   IS '활동 유형(예: PASSWORD_CHANGE, INQUIRY_WRITE 등)';
COMMENT ON COLUMN ACTIVITY_LOG.ACTION_DETAIL IS '활동 상세 내용';
COMMENT ON COLUMN ACTIVITY_LOG.ACTION_AT     IS '활동 일시';
COMMENT ON COLUMN ACTIVITY_LOG.ACTION_IP     IS '요청 IP';
COMMENT ON COLUMN ACTIVITY_LOG.USER_AGENT    IS '브라우저/기기 정보';

CREATE SEQUENCE SEQ_ACTIVITY_LOG_ID
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;

commit;