--- 이메일 인증 토큰 관리 테이블 ---

DROP TABLE EMAIL_VERIFICATION CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_EMAIL_VERIFICATION_ID;

CREATE TABLE EMAIL_VERIFICATION (
    VERIFICATION_ID   NUMBER         NOT NULL,              -- PK
    MEMBER_ID         NUMBER         NOT NULL,              -- MEMBER FK
    VERIFY_CODE       VARCHAR2(100)  NOT NULL,              -- 인증 코드 (유일 값)
    EXPIRES_AT        DATE           NOT NULL,              -- 만료 시간
    USED_YN           CHAR(1)        DEFAULT 'N' NOT NULL,  -- 사용 여부
    USED_AT           DATE,                                 -- 사용된 시각
    CREATED_AT        DATE           DEFAULT SYSDATE NOT NULL, -- 생성 시각
    
    CONSTRAINT PK_EMAIL_VERIFICATION PRIMARY KEY (VERIFICATION_ID),
    CONSTRAINT UQ_EMAIL_VERIFICATION_CODE UNIQUE (VERIFY_CODE),
    CONSTRAINT FK_EMAIL_VERIFICATION_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID)
        ON DELETE CASCADE
);

COMMENT ON TABLE EMAIL_VERIFICATION IS '이메일 인증 관리 테이블';

COMMENT ON COLUMN EMAIL_VERIFICATION.VERIFICATION_ID IS '이메일 인증 PK';
COMMENT ON COLUMN EMAIL_VERIFICATION.MEMBER_ID        IS '회원 PK (MEMBER 참조)';
COMMENT ON COLUMN EMAIL_VERIFICATION.VERIFY_CODE      IS '이메일 인증 코드';
COMMENT ON COLUMN EMAIL_VERIFICATION.EXPIRES_AT       IS '인증 코드 만료 일시';
COMMENT ON COLUMN EMAIL_VERIFICATION.USED_YN          IS '인증 코드 사용 여부(Y/N)';
COMMENT ON COLUMN EMAIL_VERIFICATION.USED_AT          IS '인증 코드 사용 일시';
COMMENT ON COLUMN EMAIL_VERIFICATION.CREATED_AT       IS '인증 요청 생성 일시';

CREATE SEQUENCE SEQ_EMAIL_VERIFICATION_ID
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;

commit;