--- 로그인 이력 테이블 ---

DROP TABLE LOGIN_HISTORY CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_LOGIN_HISTORY_ID;

CREATE TABLE LOGIN_HISTORY (
    HISTORY_ID    NUMBER        NOT NULL,
    MEMBER_ID     NUMBER        NOT NULL,
    LOGIN_AT      DATE          DEFAULT SYSDATE NOT NULL,
    LOGIN_IP      VARCHAR2(50),
    USER_AGENT    VARCHAR2(300),
    SUCCESS_YN    CHAR(1)       DEFAULT 'Y' NOT NULL,

    CONSTRAINT PK_LOGIN_HISTORY PRIMARY KEY (HISTORY_ID),
    CONSTRAINT FK_LOGIN_HISTORY_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID)
);

COMMENT ON TABLE LOGIN_HISTORY IS '회원 로그인 이력 테이블';
COMMENT ON COLUMN LOGIN_HISTORY.HISTORY_ID   IS '로그인 이력 PK';
COMMENT ON COLUMN LOGIN_HISTORY.MEMBER_ID    IS '회원 PK(MEMBER 참조)';
COMMENT ON COLUMN LOGIN_HISTORY.LOGIN_AT     IS '로그인 시각';
COMMENT ON COLUMN LOGIN_HISTORY.LOGIN_IP     IS '로그인 요청 IP';
COMMENT ON COLUMN LOGIN_HISTORY.USER_AGENT   IS '브라우저/기기 정보';
COMMENT ON COLUMN LOGIN_HISTORY.SUCCESS_YN   IS '로그인 성공 여부(Y/N)';

CREATE SEQUENCE SEQ_LOGIN_HISTORY_ID
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;

commit;
