--- 회원 테이블 ---

DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_MEMBER_ID;

CREATE TABLE MEMBER (
    MEMBER_ID          NUMBER        NOT NULL,
    LOGIN_ID           VARCHAR2(50)  NOT NULL,
    PASSWORD     VARCHAR2(255) NOT NULL,

    NAME               VARCHAR2(50)  NOT NULL,
    EMAIL              VARCHAR2(100) NOT NULL,
    PHONE              VARCHAR2(20),

    ROLE               VARCHAR2(20)  DEFAULT 'USER' NOT NULL,   -- USER / ADMIN
    EMAIL_VERIFIED_YN  CHAR(1)       DEFAULT 'N' NOT NULL,       -- 이메일 인증 여부

    CREATED_AT         DATE          DEFAULT SYSDATE NOT NULL,
    UPDATED_AT         DATE          DEFAULT SYSDATE NOT NULL,
    LAST_LOGIN_AT      DATE,
    
    PASSWORD_FAIL_COUNT NUMBER        DEFAULT 0 NOT NULL,            -- 로그인 실패 횟수
    ACCOUNT_STATUS      VARCHAR2(20)  DEFAULT 'ACTIVE' NOT NULL,      -- ACTIVE / LOCKED / BLOCKED 등


    CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID),
    CONSTRAINT UQ_MEMBER_LOGIN_ID UNIQUE (LOGIN_ID),
    CONSTRAINT UQ_MEMBER_EMAIL UNIQUE (EMAIL)
);

COMMENT ON TABLE MEMBER IS '회원 기본 정보 테이블';

COMMENT ON COLUMN MEMBER.MEMBER_ID          IS '회원 PK';
COMMENT ON COLUMN MEMBER.LOGIN_ID           IS '로그인 아이디';
COMMENT ON COLUMN MEMBER.PASSWORD      IS '비밀번호';
COMMENT ON COLUMN MEMBER.NAME               IS '회원 이름';
COMMENT ON COLUMN MEMBER.EMAIL              IS '회원 이메일';
COMMENT ON COLUMN MEMBER.PHONE              IS '휴대폰 번호';
COMMENT ON COLUMN MEMBER.ROLE               IS '회원 역할(USER/ADMIN)';
COMMENT ON COLUMN MEMBER.EMAIL_VERIFIED_YN  IS '이메일 인증 여부(Y/N)';
COMMENT ON COLUMN MEMBER.CREATED_AT         IS '생성일시';
COMMENT ON COLUMN MEMBER.UPDATED_AT         IS '수정일시';
COMMENT ON COLUMN MEMBER.LAST_LOGIN_AT      IS '마지막 로그인 시간';
COMMENT ON COLUMN MEMBER.PASSWORD_FAIL_COUNT IS '로그인 비밀번호 연속 실패 횟수';
COMMENT ON COLUMN MEMBER.ACCOUNT_STATUS      IS '계정 상태(ACTIVE/LOCKED/BLOCKED 등)';

CREATE SEQUENCE SEQ_MEMBER_ID
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;

commit;

--- 이메일 인증 토큰 관리 테이블 ---

DROP TABLE EMAIL_VERIFICATION CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_EMAIL_VERIFICATION_ID;

CREATE TABLE EMAIL_VERIFICATION (
    VERIFICATION_ID   NUMBER         NOT NULL,              -- PK
    MEMBER_ID         NUMBER         NOT NULL,              -- MEMBER FK
    VERIFY_CODE       VARCHAR2(100)  NOT NULL,              -- 인증 코드 (유일 값)
    EXPIRES_AT        DATE           NOT NULL,              -- 만료 시간
    USED_YN           CHAR(1)        DEFAULT 'N' NOT NULL,  -- 사용 여부
    USED_AT           DATE,                                 -- 사용된 시각
    CREATED_AT        DATE           DEFAULT SYSDATE NOT NULL, -- 생성 시각
    
    CONSTRAINT PK_EMAIL_VERIFICATION PRIMARY KEY (VERIFICATION_ID),
    CONSTRAINT UQ_EMAIL_VERIFICATION_CODE UNIQUE (VERIFY_CODE),
    CONSTRAINT FK_EMAIL_VERIFICATION_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID)
        ON DELETE CASCADE
);

COMMENT ON TABLE EMAIL_VERIFICATION IS '이메일 인증 관리 테이블';

COMMENT ON COLUMN EMAIL_VERIFICATION.VERIFICATION_ID IS '이메일 인증 PK';
COMMENT ON COLUMN EMAIL_VERIFICATION.MEMBER_ID        IS '회원 PK (MEMBER 참조)';
COMMENT ON COLUMN EMAIL_VERIFICATION.VERIFY_CODE      IS '이메일 인증 코드';
COMMENT ON COLUMN EMAIL_VERIFICATION.EXPIRES_AT       IS '인증 코드 만료 일시';
COMMENT ON COLUMN EMAIL_VERIFICATION.USED_YN          IS '인증 코드 사용 여부(Y/N)';
COMMENT ON COLUMN EMAIL_VERIFICATION.USED_AT          IS '인증 코드 사용 일시';
COMMENT ON COLUMN EMAIL_VERIFICATION.CREATED_AT       IS '인증 요청 생성 일시';

CREATE SEQUENCE SEQ_EMAIL_VERIFICATION_ID
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;

commit;

--- 비밀번호 재설정 관리 테이블 ---

DROP TABLE PASSWORD_RESET CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_PASSWORD_RESET_ID;

CREATE TABLE PASSWORD_RESET (
    RESET_ID      NUMBER         NOT NULL,              -- PK
    MEMBER_ID     NUMBER         NOT NULL,              -- MEMBER 참조
    RESET_CODE    VARCHAR2(100)  NOT NULL,              -- 비밀번호 재설정 코드
    EXPIRES_AT    DATE           NOT NULL,              -- 코드 만료 시간
    USED_YN       CHAR(1)        DEFAULT 'N' NOT NULL,  -- 사용 여부
    USED_AT       DATE,                                 -- 사용된 시각
    CREATED_AT    DATE           DEFAULT SYSDATE NOT NULL, -- 생성 시각

    CONSTRAINT PK_PASSWORD_RESET PRIMARY KEY (RESET_ID),
    CONSTRAINT UQ_PASSWORD_RESET_CODE UNIQUE (RESET_CODE),
    CONSTRAINT FK_PASSWORD_RESET_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID)
        ON DELETE CASCADE
);

COMMENT ON TABLE PASSWORD_RESET IS '비밀번호 재설정 관리 테이블';

COMMENT ON COLUMN PASSWORD_RESET.RESET_ID     IS '비밀번호 재설정 PK';
COMMENT ON COLUMN PASSWORD_RESET.MEMBER_ID    IS '회원 PK (MEMBER 참조)';
COMMENT ON COLUMN PASSWORD_RESET.RESET_CODE   IS '비밀번호 재설정 코드';
COMMENT ON COLUMN PASSWORD_RESET.EXPIRES_AT   IS '코드 만료 일시';
COMMENT ON COLUMN PASSWORD_RESET.USED_YN      IS '코드 사용 여부(Y/N)';
COMMENT ON COLUMN PASSWORD_RESET.USED_AT      IS '코드 사용 일시';
COMMENT ON COLUMN PASSWORD_RESET.CREATED_AT   IS '재설정 요청 생성 일시';

CREATE SEQUENCE SEQ_PASSWORD_RESET_ID
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;

commit;

--- 비밀번호 변경 이력 테이블 ---

DROP TABLE PASSWORD_CHANGE_HISTORY CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_PASSWORD_CHANGE_ID;

CREATE TABLE PASSWORD_CHANGE_HISTORY (
    CHANGE_ID     NUMBER         NOT NULL,                 -- 비밀번호 변경 이력 PK
    MEMBER_ID     NUMBER         NOT NULL,                 -- 비밀번호 변경 대상 회원
    OLD_PASSWORD  VARCHAR2(255),                           -- 변경 전 비밀번호(해시 또는 숨김 저장)
    CHANGE_TYPE   VARCHAR2(20)   NOT NULL,                 -- USER_CHANGE / ADMIN_RESET
    CHANGED_BY    NUMBER         NOT NULL,                 -- 변경 수행자 (회원 본인 또는 관리자)
    CHANGED_AT    DATE           DEFAULT SYSDATE NOT NULL, -- 변경 시각

    CONSTRAINT PK_PASSWORD_CHANGE_HISTORY PRIMARY KEY (CHANGE_ID),

    -- 변경 대상 회원
    CONSTRAINT FK_PASSWORD_CHANGE_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID),

    -- 변경 수행자 (본인이면 MEMBER_ID 동일, 관리자면 ROLE='ADMIN'인 관리자)
    CONSTRAINT FK_PASSWORD_CHANGED_BY
        FOREIGN KEY (CHANGED_BY)
        REFERENCES MEMBER(MEMBER_ID)
);

COMMENT ON TABLE PASSWORD_CHANGE_HISTORY IS '회원 비밀번호 변경 이력 테이블';

COMMENT ON COLUMN PASSWORD_CHANGE_HISTORY.CHANGE_ID    IS '비밀번호 변경 이력 PK';
COMMENT ON COLUMN PASSWORD_CHANGE_HISTORY.MEMBER_ID    IS '비밀번호 변경 대상 회원 PK';
COMMENT ON COLUMN PASSWORD_CHANGE_HISTORY.OLD_PASSWORD IS '변경 전 비밀번호(보안정책에 따라 해시/마스킹)';
COMMENT ON COLUMN PASSWORD_CHANGE_HISTORY.CHANGE_TYPE  IS '변경 유형(USER_CHANGE / ADMIN_RESET)';
COMMENT ON COLUMN PASSWORD_CHANGE_HISTORY.CHANGED_BY   IS '비밀번호 변경 수행자(회원 또는 관리자)';
COMMENT ON COLUMN PASSWORD_CHANGE_HISTORY.CHANGED_AT   IS '비밀번호 변경 시각';

CREATE SEQUENCE SEQ_PASSWORD_CHANGE_ID
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;

commit;

--- 문의 테이블 ---

DROP TABLE INQUIRY CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_INQUIRY_ID;

CREATE TABLE INQUIRY (
    INQUIRY_ID    NUMBER         NOT NULL,               -- 문의 PK
    MEMBER_ID     NUMBER         NOT NULL,               -- 문의 작성 회원
    TITLE         VARCHAR2(200)  NOT NULL,               -- 문의 제목
    CONTENT       CLOB           NOT NULL,               -- 문의 내용
    CATEGORY      VARCHAR2(50),                          -- 문의 유형(계정, 결제 등)
    STATUS        VARCHAR2(20)   DEFAULT 'RECEIVED' NOT NULL,
    -- RECEIVED / IN_PROGRESS / ANSWERED / CLOSED 등

    CREATED_AT    DATE           DEFAULT SYSDATE NOT NULL,

    CONSTRAINT PK_INQUIRY PRIMARY KEY (INQUIRY_ID),
    CONSTRAINT FK_INQUIRY_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID)
);

COMMENT ON TABLE INQUIRY IS '문의 테이블';

COMMENT ON COLUMN INQUIRY.INQUIRY_ID IS '문의 PK';
COMMENT ON COLUMN INQUIRY.MEMBER_ID  IS '문의 작성 회원 PK';
COMMENT ON COLUMN INQUIRY.TITLE      IS '문의 제목';
COMMENT ON COLUMN INQUIRY.CONTENT    IS '문의 내용';
COMMENT ON COLUMN INQUIRY.CATEGORY   IS '문의 유형';
COMMENT ON COLUMN INQUIRY.STATUS     IS '문의 상태(RECEIVED/ANSWERED 등)';
COMMENT ON COLUMN INQUIRY.CREATED_AT IS '문의 생성 일시';

CREATE SEQUENCE SEQ_INQUIRY_ID
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;

commit;

--- 답변 테이블 ---

DROP TABLE INQUIRY_ANSWER CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_INQUIRY_ANSWER_ID;

CREATE TABLE INQUIRY_ANSWER (
    ANSWER_ID      NUMBER        NOT NULL,              -- 답변 PK
    INQUIRY_ID     NUMBER        NOT NULL,              -- 어떤 문의에 대한 답변인지
    ADMIN_ID       NUMBER        NOT NULL,              -- 답변한 관리자 MEMBER_ID
    CONTENT        CLOB          NOT NULL,              -- 답변 내용
    CREATED_AT     DATE          DEFAULT SYSDATE NOT NULL,
    UPDATED_AT     DATE,

    CONSTRAINT PK_INQUIRY_ANSWER PRIMARY KEY (ANSWER_ID),

    CONSTRAINT FK_INQUIRY_ANSWER_INQUIRY
        FOREIGN KEY (INQUIRY_ID)
        REFERENCES INQUIRY(INQUIRY_ID)
        ON DELETE CASCADE,

    CONSTRAINT FK_INQUIRY_ANSWER_ADMIN
        FOREIGN KEY (ADMIN_ID)
        REFERENCES MEMBER(MEMBER_ID)
);

COMMENT ON TABLE INQUIRY_ANSWER IS '1:1 문의 답변 테이블';

COMMENT ON COLUMN INQUIRY_ANSWER.ANSWER_ID  IS '문의 답변 PK';
COMMENT ON COLUMN INQUIRY_ANSWER.INQUIRY_ID IS '답변이 달린 문의 PK';
COMMENT ON COLUMN INQUIRY_ANSWER.ADMIN_ID   IS '답변 작성 관리자 PK(MEMBER 참조)';
COMMENT ON COLUMN INQUIRY_ANSWER.CONTENT    IS '답변 내용';
COMMENT ON COLUMN INQUIRY_ANSWER.CREATED_AT IS '답변 생성 일시';
COMMENT ON COLUMN INQUIRY_ANSWER.UPDATED_AT IS '답변 수정 일시';

CREATE SEQUENCE SEQ_INQUIRY_ANSWER_ID
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;

commit;

--- 회원 탈퇴 이력 테이블 ---

DROP TABLE MEMBER_WITHDRAW CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_MEMBER_WITHDRAW_ID;

CREATE TABLE MEMBER_WITHDRAW (
    WITHDRAW_ID   NUMBER         NOT NULL,                 -- 탈퇴 이력 PK
    MEMBER_ID     NUMBER         NOT NULL,                 -- 탈퇴한 회원 PK
    REASON_CODE   VARCHAR2(50),                            -- 탈퇴 사유 코드(옵션)
    REASON_TEXT   VARCHAR2(500),                           -- 탈퇴 상세 사유(옵션)
    CREATED_AT    DATE           DEFAULT SYSDATE NOT NULL, -- 탈퇴 처리 일시

    CONSTRAINT PK_MEMBER_WITHDRAW PRIMARY KEY (WITHDRAW_ID),

    CONSTRAINT FK_MEMBER_WITHDRAW_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID)
);

COMMENT ON TABLE MEMBER_WITHDRAW IS '회원 탈퇴 이력 테이블';

COMMENT ON COLUMN MEMBER_WITHDRAW.WITHDRAW_ID IS '회원 탈퇴 이력 PK';
COMMENT ON COLUMN MEMBER_WITHDRAW.MEMBER_ID   IS '탈퇴한 회원 PK(MEMBER 참조)';
COMMENT ON COLUMN MEMBER_WITHDRAW.REASON_CODE IS '탈퇴 사유 코드(예: SERVICE, PRIVACY, OTHER 등)';
COMMENT ON COLUMN MEMBER_WITHDRAW.REASON_TEXT IS '사용자가 입력한 탈퇴 상세 사유';
COMMENT ON COLUMN MEMBER_WITHDRAW.CREATED_AT  IS '탈퇴 처리 일시';

CREATE SEQUENCE SEQ_MEMBER_WITHDRAW_ID
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;

commit;

--- 로그인 이력 테이블 ---

DROP TABLE LOGIN_HISTORY CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_LOGIN_HISTORY_ID;

CREATE TABLE LOGIN_HISTORY (
    HISTORY_ID    NUMBER        NOT NULL,
    MEMBER_ID     NUMBER        NOT NULL,
    LOGIN_AT      DATE          DEFAULT SYSDATE NOT NULL,
    LOGIN_IP      VARCHAR2(50),
    USER_AGENT    VARCHAR2(300),
    SUCCESS_YN    CHAR(1)       DEFAULT 'Y' NOT NULL,

    CONSTRAINT PK_LOGIN_HISTORY PRIMARY KEY (HISTORY_ID),
    CONSTRAINT FK_LOGIN_HISTORY_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID)
);

COMMENT ON TABLE LOGIN_HISTORY IS '회원 로그인 이력 테이블';
COMMENT ON COLUMN LOGIN_HISTORY.HISTORY_ID   IS '로그인 이력 PK';
COMMENT ON COLUMN LOGIN_HISTORY.MEMBER_ID    IS '회원 PK(MEMBER 참조)';
COMMENT ON COLUMN LOGIN_HISTORY.LOGIN_AT     IS '로그인 시각';
COMMENT ON COLUMN LOGIN_HISTORY.LOGIN_IP     IS '로그인 요청 IP';
COMMENT ON COLUMN LOGIN_HISTORY.USER_AGENT   IS '브라우저/기기 정보';
COMMENT ON COLUMN LOGIN_HISTORY.SUCCESS_YN   IS '로그인 성공 여부(Y/N)';

CREATE SEQUENCE SEQ_LOGIN_HISTORY_ID
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;

commit;

--- 회원 활동 로그 테이블 ---

DROP TABLE ACTIVITY_LOG CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_ACTIVITY_LOG_ID;

CREATE TABLE ACTIVITY_LOG (
    LOG_ID        NUMBER         NOT NULL,              -- 활동 로그 PK
    MEMBER_ID     NUMBER         NOT NULL,              -- 활동한 회원
    ACTION_TYPE   VARCHAR2(100)  NOT NULL,              -- 활동 유형
    ACTION_DETAIL VARCHAR2(500),                        -- 상세 내용(선택)
    ACTION_AT     DATE           DEFAULT SYSDATE NOT NULL, -- 활동 일시
    ACTION_IP     VARCHAR2(50),                         -- 행동 IP
    USER_AGENT    VARCHAR2(300),                        -- 브라우저/기기 정보

    CONSTRAINT PK_ACTIVITY_LOG PRIMARY KEY (LOG_ID),
    CONSTRAINT FK_ACTIVITY_LOG_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID)
);

COMMENT ON TABLE ACTIVITY_LOG IS '회원 활동 로그 테이블';

COMMENT ON COLUMN ACTIVITY_LOG.LOG_ID        IS '활동 로그 PK';
COMMENT ON COLUMN ACTIVITY_LOG.MEMBER_ID     IS '회원 PK(MEMBER 참조)';
COMMENT ON COLUMN ACTIVITY_LOG.ACTION_TYPE   IS '활동 유형(예: PASSWORD_CHANGE, INQUIRY_WRITE 등)';
COMMENT ON COLUMN ACTIVITY_LOG.ACTION_DETAIL IS '활동 상세 내용';
COMMENT ON COLUMN ACTIVITY_LOG.ACTION_AT     IS '활동 일시';
COMMENT ON COLUMN ACTIVITY_LOG.ACTION_IP     IS '요청 IP';
COMMENT ON COLUMN ACTIVITY_LOG.USER_AGENT    IS '브라우저/기기 정보';

CREATE SEQUENCE SEQ_ACTIVITY_LOG_ID
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;

commit;

--- 회원 서비스 전용 에러 로그 테이블 ---

DROP TABLE MEMBER_ERROR_LOG CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_MEMBER_ERROR_LOG_ID;

CREATE TABLE MEMBER_ERROR_LOG (
    ERROR_ID      NUMBER          NOT NULL,                -- 에러 PK
    MEMBER_ID     NUMBER          NOT NULL,                 -- 회원 PK
    ERROR_MESSAGE VARCHAR2(1000)  NOT NULL,                 -- 에러 요약 메시지
    STACK_TRACE   CLOB,                                     -- 에러 상세 스택 (옵션)
    ERROR_AT      DATE           DEFAULT SYSDATE NOT NULL,  -- 에러 발생 시각
    REQUEST_URI   VARCHAR2(300),                            -- 요청 URL
    METHOD        VARCHAR2(10),                             -- HTTP 메서드(GET/POST 등)
    REQUEST_IP    VARCHAR2(50),                             -- 요청한 IP
    USER_AGENT    VARCHAR2(300),                            -- 브라우저/기기 정보

    CONSTRAINT PK_MEMBER_ERROR_LOG PRIMARY KEY (ERROR_ID),

    CONSTRAINT FK_MEMBER_ERROR_LOG_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID)
);

COMMENT ON TABLE MEMBER_ERROR_LOG IS '회원 서비스 에러 로그 테이블';

COMMENT ON COLUMN MEMBER_ERROR_LOG.ERROR_ID      IS '회원 서비스 에러 로그 PK';
COMMENT ON COLUMN MEMBER_ERROR_LOG.MEMBER_ID     IS '요청한 회원 PK(비회원 요청 시 NULL)';
COMMENT ON COLUMN MEMBER_ERROR_LOG.ERROR_MESSAGE IS '에러 요약 메시지';
COMMENT ON COLUMN MEMBER_ERROR_LOG.STACK_TRACE   IS '에러 스택 상세 정보';
COMMENT ON COLUMN MEMBER_ERROR_LOG.ERROR_AT      IS '에러 발생 시각';
COMMENT ON COLUMN MEMBER_ERROR_LOG.REQUEST_URI   IS '요청 URI';
COMMENT ON COLUMN MEMBER_ERROR_LOG.METHOD        IS 'HTTP 요청 메서드';
COMMENT ON COLUMN MEMBER_ERROR_LOG.REQUEST_IP    IS '요청 IP';
COMMENT ON COLUMN MEMBER_ERROR_LOG.USER_AGENT    IS '요청 브라우저/기기 정보';

CREATE SEQUENCE SEQ_MEMBER_ERROR_LOG_ID
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;

commit;

--- 회원 정보 수정 이력 테이블 --- 
DROP TABLE MEMBER_UPDATE_HISTORY CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_MEMBER_UPDATE_HISTORY_ID;

CREATE TABLE MEMBER_UPDATE_HISTORY (
    HISTORY_ID     NUMBER          NOT NULL,                 -- 이력 PK
    MEMBER_ID      NUMBER          NOT NULL,                 -- 대상 회원
    FIELD_NAME     VARCHAR2(100)   NOT NULL,                 -- 변경된 필드명 (EMAIL, PHONE 등)
    OLD_VALUE      VARCHAR2(500),                             -- 이전 값
    NEW_VALUE      VARCHAR2(500),                             -- 새 값
    CHANGED_BY     NUMBER          NOT NULL,                 -- 변경한 회원(본인 or 관리자)
    CHANGE_TYPE    VARCHAR2(20)    NOT NULL,                 -- USER_CHANGE / ADMIN_CHANGE
    CHANGED_AT     DATE            DEFAULT SYSDATE NOT NULL, -- 변경 시각

    CONSTRAINT PK_MEMBER_UPDATE_HISTORY PRIMARY KEY (HISTORY_ID),

    -- 변경 대상 회원
    CONSTRAINT FK_MEMBER_UPDATE_HISTORY_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID),

    -- 변경 수행자 (본인 또는 관리자)
    CONSTRAINT FK_MEMBER_UPDATE_HISTORY_CHANGEDBY
        FOREIGN KEY (CHANGED_BY)
        REFERENCES MEMBER(MEMBER_ID)
);

COMMENT ON TABLE MEMBER_UPDATE_HISTORY IS '회원 정보 수정 이력 테이블';

COMMENT ON COLUMN MEMBER_UPDATE_HISTORY.HISTORY_ID   IS '회원 정보 수정 이력 PK';
COMMENT ON COLUMN MEMBER_UPDATE_HISTORY.MEMBER_ID    IS '개인정보가 수정된 회원 PK';
COMMENT ON COLUMN MEMBER_UPDATE_HISTORY.FIELD_NAME   IS '수정된 필드명(예: EMAIL, PHONE, NAME)';
COMMENT ON COLUMN MEMBER_UPDATE_HISTORY.OLD_VALUE    IS '변경 전 값';
COMMENT ON COLUMN MEMBER_UPDATE_HISTORY.NEW_VALUE    IS '변경 후 값';
COMMENT ON COLUMN MEMBER_UPDATE_HISTORY.CHANGED_BY   IS '수정을 수행한 회원(본인 또는 관리자)';
COMMENT ON COLUMN MEMBER_UPDATE_HISTORY.CHANGE_TYPE  IS '수정 유형(USER_CHANGE / ADMIN_CHANGE)';
COMMENT ON COLUMN MEMBER_UPDATE_HISTORY.CHANGED_AT   IS '수정 시각';

CREATE SEQUENCE SEQ_MEMBER_UPDATE_HISTORY_ID
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;

commit;
