--- 회원 정보 수정 이력 테이블 --- 
DROP TABLE MEMBER_UPDATE_HISTORY CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_MEMBER_UPDATE_HISTORY_ID;

CREATE TABLE MEMBER_UPDATE_HISTORY (
    HISTORY_ID     NUMBER          NOT NULL,                 -- 이력 PK
    MEMBER_ID      NUMBER          NOT NULL,                 -- 대상 회원
    FIELD_NAME     VARCHAR2(100)   NOT NULL,                 -- 변경된 필드명 (EMAIL, PHONE 등)
    OLD_VALUE      VARCHAR2(500),                             -- 이전 값
    NEW_VALUE      VARCHAR2(500),                             -- 새 값
    CHANGED_BY     NUMBER          NOT NULL,                 -- 변경한 회원(본인 or 관리자)
    CHANGE_TYPE    VARCHAR2(20)    NOT NULL,                 -- USER_CHANGE / ADMIN_CHANGE
    CHANGED_AT     DATE            DEFAULT SYSDATE NOT NULL, -- 변경 시각

    CONSTRAINT PK_MEMBER_UPDATE_HISTORY PRIMARY KEY (HISTORY_ID),

    -- 변경 대상 회원
    CONSTRAINT FK_MEMBER_UPDATE_HISTORY_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID),

    -- 변경 수행자 (본인 또는 관리자)
    CONSTRAINT FK_MEMBER_UPDATE_HISTORY_CHANGEDBY
        FOREIGN KEY (CHANGED_BY)
        REFERENCES MEMBER(MEMBER_ID)
);

COMMENT ON TABLE MEMBER_UPDATE_HISTORY IS '회원 정보 수정 이력 테이블';

COMMENT ON COLUMN MEMBER_UPDATE_HISTORY.HISTORY_ID   IS '회원 정보 수정 이력 PK';
COMMENT ON COLUMN MEMBER_UPDATE_HISTORY.MEMBER_ID    IS '개인정보가 수정된 회원 PK';
COMMENT ON COLUMN MEMBER_UPDATE_HISTORY.FIELD_NAME   IS '수정된 필드명(예: EMAIL, PHONE, NAME)';
COMMENT ON COLUMN MEMBER_UPDATE_HISTORY.OLD_VALUE    IS '변경 전 값';
COMMENT ON COLUMN MEMBER_UPDATE_HISTORY.NEW_VALUE    IS '변경 후 값';
COMMENT ON COLUMN MEMBER_UPDATE_HISTORY.CHANGED_BY   IS '수정을 수행한 회원(본인 또는 관리자)';
COMMENT ON COLUMN MEMBER_UPDATE_HISTORY.CHANGE_TYPE  IS '수정 유형(USER_CHANGE / ADMIN_CHANGE)';
COMMENT ON COLUMN MEMBER_UPDATE_HISTORY.CHANGED_AT   IS '수정 시각';

CREATE SEQUENCE SEQ_MEMBER_UPDATE_HISTORY_ID
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;

commit;
