-- 권한 종류 테이블

DROP TABLE ROLE CASCADE CONSTRAINTS;

CREATE TABLE ROLE (
    ROLE_ID    NUMBER(10)       NOT NULL,
    ROLE_NAME  VARCHAR2(100)    NOT NULL,
    
    CONSTRAINT PK_ROLE PRIMARY KEY (ROLE_ID),
    CONSTRAINT UQ_ROLE_NAME UNIQUE (ROLE_NAME)
);


-- INSERT
INSERT INTO ROLE (ROLE_NAME) 
VALUES ('USER');

INSERT INTO ROLE (ROLE_NAME) 
VALUES ('ADMIN');

-- SELECT
SELECT *
FROM ROLE
ORDER BY ROLE_ID;

-- UPDATE
UPDATE ROLE
SET ROLE_NAME = 'SUPER_ADMIN'
WHERE ROLE_ID = 2;

-- DELETE
DELETE FROM ROLE
WHERE ROLE_ID = 3;


