DROP TABLE CHAT_MESSAGE_REF CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_CHAT_MESSAGE_REF_ID;

CREATE TABLE CHAT_MESSAGE_REF (
  REF_ID     NUMBER NOT NULL,
  CHAT_ID    NUMBER NOT NULL,   -- CHAT_HISTORY.chat_id
  CHUNK_ID   NUMBER NOT NULL,
  SCORE      NUMBER(10,6) NOT NULL,
  CREATED_AT DATE DEFAULT SYSDATE NOT NULL,

  CONSTRAINT PK_CHAT_MESSAGE_REF PRIMARY KEY (REF_ID),
  CONSTRAINT FK_CHAT_MESSAGE_REF_CHAT FOREIGN KEY (CHAT_ID) REFERENCES CHAT_MESSAGE(CHAT_ID),
  CONSTRAINT FK_CHAT_MESSAGE_REF_CHUNK FOREIGN KEY (CHUNK_ID) REFERENCES EMBEDDING_CHUNK(CHUNK_ID)
);

CREATE INDEX IDX_CHAT_MESSAGE_REF_CHAT ON CHAT_MESSAGE_REF(CHAT_ID);


CREATE SEQUENCE SEQ_CHAT_MESSAGE_REF_ID
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
CACHE 2
NOCYCLE;


-- 1) 테이블 존재 확인 (내 스키마)
SELECT table_name
FROM user_tables
WHERE table_name IN ('CHAT_HISTORY', 'EMBEDDING_CHUNK');

-- 2) 컬럼 존재 확인 (CHAT_HISTORY)
SELECT column_name
FROM user_tab_columns
WHERE table_name = 'CHAT_HISTORY';

-- 3) 컬럼 존재 확인 (EMBEDDING_CHUNK)
SELECT column_name
FROM user_tab_columns
WHERE table_name = 'EMBEDDING_CHUNK';

