--- 비밀번호 변경 이력 테이블 ---

DROP TABLE PASSWORD_CHANGE_HISTORY CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_PASSWORD_CHANGE_HISTORY_ID;

CREATE TABLE PASSWORD_CHANGE_HISTORY (
    CHANGE_ID     NUMBER         NOT NULL,                 -- 비밀번호 변경 이력 PK
    MEMBER_ID     NUMBER         NOT NULL,                 -- 비밀번호 변경 대상 회원
    OLD_PASSWORD  VARCHAR2(255),                           -- 변경 전 비밀번호(해시 또는 숨김 저장)
    CHANGE_TYPE   VARCHAR2(20)   NOT NULL,                 -- USER_CHANGE / ADMIN_RESET
    CHANGED_BY    NUMBER         NOT NULL,                 -- 변경 수행자 (회원 본인 또는 관리자)
    CHANGED_AT    DATE           DEFAULT SYSDATE NOT NULL, -- 변경 시각

    CONSTRAINT PK_PASSWORD_CHANGE_HISTORY PRIMARY KEY (CHANGE_ID),

    -- 변경 대상 회원
    CONSTRAINT FK_PASSWORD_CHANGE_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID),

    -- 변경 수행자 (본인이면 MEMBER_ID 동일, 관리자면 ROLE='ADMIN'인 관리자)
    CONSTRAINT FK_PASSWORD_CHANGED_BY
        FOREIGN KEY (CHANGED_BY)
        REFERENCES MEMBER(MEMBER_ID)
);

COMMENT ON TABLE PASSWORD_CHANGE_HISTORY IS '회원 비밀번호 변경 이력 테이블';

COMMENT ON COLUMN PASSWORD_CHANGE_HISTORY.CHANGE_ID    IS '비밀번호 변경 이력 PK';
COMMENT ON COLUMN PASSWORD_CHANGE_HISTORY.MEMBER_ID    IS '비밀번호 변경 대상 회원 PK';
COMMENT ON COLUMN PASSWORD_CHANGE_HISTORY.OLD_PASSWORD IS '변경 전 비밀번호(보안정책에 따라 해시/마스킹)';
COMMENT ON COLUMN PASSWORD_CHANGE_HISTORY.CHANGE_TYPE  IS '변경 유형(USER_CHANGE / ADMIN_RESET)';
COMMENT ON COLUMN PASSWORD_CHANGE_HISTORY.CHANGED_BY   IS '비밀번호 변경 수행자(회원 또는 관리자)';
COMMENT ON COLUMN PASSWORD_CHANGE_HISTORY.CHANGED_AT   IS '비밀번호 변경 시각';

CREATE SEQUENCE SEQ_PASSWORD_CHANGE_HISTORY_ID
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

commit;
