--- 회원 탈퇴 이력 테이블 ---

DROP TABLE MEMBER_WITHDRAW CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_MEMBER_WITHDRAW_ID;

CREATE TABLE MEMBER_WITHDRAW (
    WITHDRAW_ID   NUMBER         NOT NULL,                 -- 탈퇴 이력 PK
    MEMBER_ID     NUMBER         NOT NULL,                 -- 탈퇴한 회원 PK
    REASON_CODE   VARCHAR2(50),                            -- 탈퇴 사유 코드(옵션)
    REASON_TEXT   VARCHAR2(500),                           -- 탈퇴 상세 사유(옵션)
    CREATED_AT    DATE           DEFAULT SYSDATE NOT NULL, -- 탈퇴 처리 일시

    CONSTRAINT PK_MEMBER_WITHDRAW PRIMARY KEY (WITHDRAW_ID),

    CONSTRAINT FK_MEMBER_WITHDRAW_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID)
);

COMMENT ON TABLE MEMBER_WITHDRAW IS '회원 탈퇴 이력 테이블';

COMMENT ON COLUMN MEMBER_WITHDRAW.WITHDRAW_ID IS '회원 탈퇴 이력 PK';
COMMENT ON COLUMN MEMBER_WITHDRAW.MEMBER_ID   IS '탈퇴한 회원 PK(MEMBER 참조)';
COMMENT ON COLUMN MEMBER_WITHDRAW.REASON_CODE IS '탈퇴 사유 코드(예: SERVICE, PRIVACY, OTHER 등)';
COMMENT ON COLUMN MEMBER_WITHDRAW.REASON_TEXT IS '사용자가 입력한 탈퇴 상세 사유';
COMMENT ON COLUMN MEMBER_WITHDRAW.CREATED_AT  IS '탈퇴 처리 일시';

CREATE SEQUENCE SEQ_MEMBER_WITHDRAW_ID
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;

commit;