-- 회원이 가진 권한 매핑 테이블

DROP TABLE MEMBER_ROLE CASCADE CONSTRAINTS;

CREATE TABLE MEMBER_ROLE (
    MEMBER_ID   NUMBER(10)      NOT NULL,
    ROLE_ID     NUMBER(10)      NOT NULL,

    CONSTRAINT PK_MEMBER_ROLE PRIMARY KEY (MEMBER_ID, ROLE_ID),

    CONSTRAINT FK_MEMBER_ROLE_MEMBER 
        FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),

    CONSTRAINT FK_MEMBER_ROLE_ROLE 
        FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ROLE_ID)
);


-- 회원에게 권한 부여
INSERT INTO MEMBER_ROLE (MEMBER_ID, ROLE_ID)
VALUES (1, 2);


-- 특정 회원이 가진 전체 권한 보기
SELECT r.ROLE_NAME
FROM MEMBER_ROLE mr
JOIN ROLE r ON mr.ROLE_ID = r.ROLE_ID
WHERE mr.MEMBER_ID = 1;

-- 특정 권한을 가진 사용자 목록 조회
SELECT m.MEMBER_ID, m.LOGIN_ID, m.EMAIL, r.ROLE_NAME
FROM MEMBER_ROLE mr
JOIN MEMBER m ON mr.MEMBER_ID = m.MEMBER_ID
JOIN ROLE r ON mr.ROLE_ID = r.ROLE_ID
WHERE r.ROLE_NAME = 'ADMIN';

-- 권한 삭제
DELETE FROM MEMBER_ROLE
WHERE MEMBER_ID = 1
  AND ROLE_ID = 2;

-- 해당 사용자가 관리자인지 확인 - 1이상: 관리자, 0: 회원
SELECT COUNT(*) 
FROM MEMBER_ROLE mr
JOIN ROLE r ON mr.ROLE_ID = r.ROLE_ID
WHERE mr.MEMBER_ID = :member_id
  AND r.ROLE_NAME = 'ADMIN';

-- 회원 가입시 기본 MEMBER 권한 부여
INSERT INTO MEMBER (LOGIN_ID, EMAIL, PASSWORD, NAME)
VALUES ('user55', 'user55@mail.com', 'pw', '이몽룡');
INSERT INTO MEMBER_ROLE (MEMBER_ID, ROLE_ID)
VALUES (:new_member_id, (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME='USER'));

-- 회원 권한 전체 조회(관리자 페이지용)
SELECT 
    m.MEMBER_ID,
    m.LOGIN_ID,
    m.EMAIL,
    LISTAGG(r.ROLE_NAME, ', ') WITHIN GROUP (ORDER BY r.ROLE_NAME) AS ROLES
FROM MEMBER m
LEFT JOIN MEMBER_ROLE mr ON m.MEMBER_ID = mr.MEMBER_ID
LEFT JOIN ROLE r ON mr.ROLE_ID = r.ROLE_ID
GROUP BY m.MEMBER_ID, m.LOGIN_ID, m.EMAIL
ORDER BY m.MEMBER_ID;

-- 권한 일괄 변경(관리자 페이지용)
-- 삭제
DELETE FROM MEMBER_ROLE
WHERE MEMBER_ID = :member_id;
-- 특정 회원에게 여러 권한 부여
INSERT INTO MEMBER_ROLE (MEMBER_ID, ROLE_ID)
VALUES (:member_id, :role_id);



