DROP TABLE CHAT_SESSION CASCADE CONSTRAINTS;

CREATE TABLE CHAT_SESSION (
  SESSION_ID        NUMBER         NOT NULL,
  MEMBER_ID         NUMBER         NOT NULL,

  TITLE             VARCHAR2(200),
  SESSION_STATUS    VARCHAR2(20)   DEFAULT 'ACTIVE' NOT NULL,  -- ACTIVE/ARCHIVED/DELETED

  START_TIME        DATE           DEFAULT SYSDATE NOT NULL,
  END_TIME          DATE,

  LAST_MESSAGE_AT   DATE           DEFAULT SYSDATE NOT NULL,
  DELETED_AT        DATE,

  CONSTRAINT PK_CHAT_SESSION PRIMARY KEY (SESSION_ID),
  CONSTRAINT FK_CHAT_SESSION_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID)
);

COMMENT ON TABLE CHAT_SESSION IS '챗봇 대화 세션(대화방)';
COMMENT ON COLUMN CHAT_SESSION.SESSION_ID IS '세션 PK';
COMMENT ON COLUMN CHAT_SESSION.MEMBER_ID IS '회원 PK (MEMBER.MEMBER_ID)';
COMMENT ON COLUMN CHAT_SESSION.SESSION_STATUS IS 'ACTIVE/ARCHIVED/DELETED';
COMMENT ON COLUMN CHAT_SESSION.LAST_MESSAGE_AT IS '최근 메시지 시간(정렬/최근대화용)';
COMMENT ON COLUMN CHAT_SESSION.DELETED_AT IS '소프트 삭제 시간';

DROP SEQUENCE SEQ_SESSION_ID;

CREATE SEQUENCE SEQ_SESSION_ID
  START WITH 1                  -- 시작 번호
  INCREMENT BY 1                -- 증가값
  MAXVALUE 9999999999           -- 최대값: 9999999999 --> NUMBER(10) 대응
  CACHE 2                       -- 2번은 메모리에서만 계산
  NOCYCLE;                      -- 다시 1부터 생성되는 것을 방지
  
-- ✅ 세션 목록 조회 성능용 인덱스
CREATE INDEX IDX_CHAT_SESSION_MEMBER_LAST
  ON CHAT_SESSION (MEMBER_ID, LAST_MESSAGE_AT DESC);
  